### ISSUE TITLE
Worker not working: AttributeError: async

### ISSUE THREAD

**Issue by devlinrcg** [Netflix/security_monkey#1073]
## Please make sure that you have checked the boxes: 

- [X ] [Pease review the Troubleshooting doc for additional details regarding your issue.](https://github.com/Netflix/security_monkey/blob/develop/docs/troubleshooting.md)
- [X ] Review the [Quickstart guide](https://github.com/Netflix/security_monkey/blob/develop/docs/quickstart.md)
- [X ] [Search for both open and closed issues](https://github.com/Netflix/security_monkey/issues?&q=is%3Aissue+) regarding the problem you are experiencing
- [ ] **For permissions issues** (Access Denied and credential related errors), please refer to the requisite docs before submitting an issue:
[AWS](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_aws.md), [GCP](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_gcp.md), [OpenStack](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_openstack.md), [GitHub](https://github.com/Netflix/security_monkey/blob/develop/docs/github_setup.md#access-keys-and-permissions)

## Description of issue:

Hey guys!

I followed everything in the QuickStart and Autostarting documentation, but my Worker process on Supervisor always gets a FATAL Exited too quickly message.

Here is the log section on securitymonkeyworkers-stderr:

`/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/Flask_SQLAlchemy-1.0-py2.7.egg/flask_sqlalchemy/__init__.py:30: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  from flask.ext.sqlalchemy._compat import iteritems, itervalues, xrange, \
/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/Flask_SQLAlchemy-1.0-py2.7.egg/flask_sqlalchemy/__init__.py:30: ExtDeprecationWarning: Importing flask.ext.sqlalchemy._compat is deprecated, use flask_sqlalchemy._compat instead.
  from flask.ext.sqlalchemy._compat import iteritems, itervalues, xrange, \
/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/psycopg2-2.7.4-py2.7-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "/usr/local/src/security_monkey/venv/bin/celery", line 11, in <module>
    load_entry_point('celery', 'console_scripts', 'celery')()
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/celery-4.2.0rc2-py2.7.egg/celery/__main__.py", line 16, in main
    _main()
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/celery-4.2.0rc2-py2.7.egg/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/celery-4.2.0rc2-py2.7.egg/celery/bin/celery.py", line 484, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/celery-4.2.0rc2-py2.7.egg/celery/bin/base.py", line 275, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/celery-4.2.0rc2-py2.7.egg/celery/bin/celery.py", line 476, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/celery-4.2.0rc2-py2.7.egg/celery/bin/celery.py", line 408, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/celery-4.2.0rc2-py2.7.egg/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/celery-4.2.0rc2-py2.7.egg/celery/bin/base.py", line 238, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/celery-4.2.0rc2-py2.7.egg/celery/bin/worker.py", line 257, in run
    **kwargs)
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/celery-4.2.0rc2-py2.7.egg/celery/worker/worker.py", line 101, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/celery-4.2.0rc2-py2.7.egg/celery/worker/worker.py", line 124, in setup_instance
    self.should_use_eventloop() if use_eventloop is None
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/celery-4.2.0rc2-py2.7.egg/celery/worker/worker.py", line 243, in should_use_eventloop
    self._conninfo.transport.implements.async and
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/kombu-4.2.0-py2.7.egg/kombu/transport/base.py", line 125, in __getattr__
    raise AttributeError(key)
AttributeError: async`

I have two test accounts (AWS and GCP), and running monkey find -a gets everything done.
Weird, right?

Please let me known if you have any thoughts on this...

**Comment by mikegrima** [comment]
Yes -- I have reproduced this.

We need to upgrade to the latest celery RC.  PR and release coming soon.

**Comment by mikegrima** [comment]
This PR should fix: https://github.com/Netflix/security_monkey/pull/1074

**Comment by mikegrima** [comment]
@devlinrcg : can you try with the latest develop branch?

**Comment by devlinrcg** [comment]
Thank you for your reply on this, @mikegrima !
I'll give it a try and let you guys know in a few.

**Comment by devlinrcg** [comment]
Yep, worked with the latest develop branch.
Getting another error, related to https://github.com/Netflix/security_monkey/issues/1038. I'll follow-up there.

Thank you once again, @mikegrima
