### ISSUE TITLE
monkey db upgrade fails

### ISSUE THREAD

**Issue by httpnotonly** [Netflix/security_monkey#1194]
## Please make sure that you have checked the boxes: 

- [ + ] [Pease review the Troubleshooting doc for additional details regarding your issue.](https://github.com/Netflix/security_monkey/blob/develop/docs/troubleshooting.md)
- [ + ] Review the [Quickstart guide](https://github.com/Netflix/security_monkey/blob/develop/docs/quickstart.md)
- [ + ] [Search for both open and closed issues](https://github.com/Netflix/security_monkey/issues?&q=is%3Aissue+) regarding the problem you are experiencing

 **Looks like continue of this**  https://github.com/Netflix/security_monkey/issues/1191

- [ + ] **For permissions issues** (Access Denied and credential related errors), please refer to the requisite docs before submitting an issue:
[AWS](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_aws.md), [GCP](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_gcp.md), [OpenStack](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_openstack.md), [GitHub](https://github.com/Netflix/security_monkey/blob/develop/docs/github_setup.md#access-keys-and-permissions)

## Description of issue:
Hi team, i'm trying to run python comands, but have sentry errors and this one:
``` 
5.0.0a1-py2.7.egg/vine/abstract.py", line 8
    class Thenable(Callable, metaclass=abc.ABCMeta):  # pragma: no cover
                                      ^
SyntaxError: invalid syntax
```
The full log is
```
(venv) ubuntu@ip-xxxxxxx:/usr/local/src/security_monkey$ monkey db upgrade
/usr/local/src/security_monkey/security_monkey/venv/lib/python2.7/site-packages/Flask_SQLAlchemy-1.0-py2.7.egg/flask_sqlalchemy/__init__.py:30: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  from flask.ext.sqlalchemy._compat import iteritems, itervalues, xrange, \
/usr/local/src/security_monkey/security_monkey/venv/lib/python2.7/site-packages/Flask_SQLAlchemy-1.0-py2.7.egg/flask_sqlalchemy/__init__.py:30: ExtDeprecationWarning: Importing flask.ext.sqlalchemy._compat is deprecated, use flask_sqlalchemy._compat instead.
  from flask.ext.sqlalchemy._compat import iteritems, itervalues, xrange, \
/usr/local/src/security_monkey/security_monkey/venv/lib/python2.7/site-packages/psycopg2-2.7.4-py2.7-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
2019-04-04 11:53:38,769 DEBUG: Sentry not installed, skipping... [in /usr/local/src/security_monkey/security_monkey/__init__.py:369]
Traceback (most recent call last):
  File "/usr/local/src/security_monkey/security_monkey/venv/bin/monkey", line 11, in <module>
    load_entry_point('security-monkey', 'console_scripts', 'monkey')()
  File "/usr/local/src/security_monkey/security_monkey/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/src/security_monkey/security_monkey/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/local/src/security_monkey/security_monkey/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/local/src/security_monkey/security_monkey/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/src/security_monkey/security_monkey/manage.py", line 31, in <module>
    from security_monkey.task_scheduler.tasks import manual_run_change_reporter, manual_run_change_finder
  File "/usr/local/src/security_monkey/security_monkey/task_scheduler/tasks.py", line 28, in <module>
    from security_monkey.task_scheduler.util import CELERY, setup
  File "/usr/local/src/security_monkey/security_monkey/task_scheduler/util.py", line 11, in <module>
    from celery import Celery
  File "/usr/local/src/security_monkey/security_monkey/venv/lib/python2.7/site-packages/celery-4.2.2-py2.7.egg/celery/__init__.py", line 150, in <module>
    from . import local  # noqa
  File "/usr/local/src/security_monkey/security_monkey/venv/lib/python2.7/site-packages/celery-4.2.2-py2.7.egg/celery/local.py", line 17, in <module>
    from .five import PY3, bytes_if_py2, items, string, string_t
  File "/usr/local/src/security_monkey/security_monkey/venv/lib/python2.7/site-packages/celery-4.2.2-py2.7.egg/celery/five.py", line 7, in <module>
    import vine.five
  File "/usr/local/src/security_monkey/security_monkey/venv/lib/python2.7/site-packages/vine-5.0.0a1-py2.7.egg/vine/__init__.py", line 6, in <module>
    from .abstract import Thenable
  File "/usr/local/src/security_monkey/security_monkey/venv/lib/python2.7/site-packages/vine-5.0.0a1-py2.7.egg/vine/abstract.py", line 8
    class Thenable(Callable, metaclass=abc.ABCMeta):  # pragma: no cover
                                      ^
SyntaxError: invalid syntax
```

**Comment by mstair** [comment]
This is an issue due to the celery dependency vine upgrade to vine-5.0.0a1 few days ago, where it removed py2 support (https://github.com/celery/vine/releases). Just submitted PR #1195 to pin vine to 1.3.0 (verified addresses by user on gitter).

**Comment by httpnotonly** [comment]
Yep, now it works.
Hope, PR checks will be done :)

**Comment by httpnotonly** [comment]
For googlers
pip install vine==1.3.0
