### ISSUE TITLE
error when running monkey db upgrade

### ISSUE THREAD

**Issue by erick2k1995** [Netflix/security_monkey#1215]
error when running monkey db upgrade help please this comes out.
```
(venv) ubuntu @ ip-172-31-35-45: / usr / local / src / security_monkey $ monkey db upgrade
Traceback (most recent call last):
  File "/ usr / local / src / security_monkey / venv / bin / monkey", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f (* args, ** kwargs)
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master ()
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements (__ requires__)
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve (reqs, Environment ())
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict (dist, req) .with_context (dependent_req)
pkg_resources.ContextualVersionConflict: (defusedxml 0.6.0 (/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/defusedxml-0.6.0-py2.7.egg), Requirement.parse ('defusedxml == 0.5.0 '), set ([' cloudaux ']))
```

**Comment by mikegrima** [comment]
Confirmed I'm having the issue as well.

**Comment by mikegrima** [comment]
I'm going to update the dependency for CloudAux.

**Comment by erick2k1995** [comment]
@mikegrima and I could solve it effectively by updating the dependency

**Comment by mikegrima** [comment]
Uninstall the old `cloudaux`, and install `1.6.4`
