### ISSUE TITLE
monkey db upgrade fails

### ISSUE THREAD

**Issue by siddheshsalunke** [Netflix/security_monkey#1236]
## Please make sure that you have checked the boxes: 
- [x]  [Pease review the Troubleshooting doc for additional details regarding your issue.](https://github.com/Netflix/security_monkey/blob/develop/docs/troubleshooting.md)

- [x] Review the [Quickstart guide](https://github.com/Netflix/security_monkey/blob/develop/docs/quickstart.md)
- [x] [Search for both open and closed issues](https://github.com/Netflix/security_monkey/issues?&q=is%3Aissue+) regarding the problem you are experiencing
- [x] **For permissions issues** (Access Denied and credential related errors), please refer to the requisite docs before submitting an issue:
[AWS](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_aws.md), [GCP](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_gcp.md), [OpenStack](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_openstack.md), [GitHub](https://github.com/Netflix/security_monkey/blob/develop/docs/github_setup.md#access-keys-and-permissions)

## Description of issue:

Hi team, i'm trying to run:

```
monkey db upgrade
```

And getting error like:

```
Traceback (most recent call last):
  File "/usr/local/bin/monkey", line 11, in <module>
    load_entry_point('security-monkey', 'console_scripts', 'monkey')()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/security_monkey-1.1.1-py3.6.egg/security_monkey/__init__.py", line 247, in <module>
    from security_monkey.export import export_blueprint
  File "/usr/local/lib/python3.6/dist-packages/security_monkey-1.1.1-py3.6.egg/security_monkey/export/__init__.py", line 127
    search = args['searchconfig'].split(',')
                                           ^
TabError: inconsistent use of tabs and spaces in indentation
```

What looks like probable issue?

**Comment by mikegrima** [comment]
Is this from the latest git pull?

**Comment by mikegrima** [comment]
Looking at the source code of the file, I don't see any tab characters in there.
