### ISSUE TITLE
ALB/ELB scans are not working

### ISSUE THREAD

**Issue by Deepak1100** [Netflix/security_monkey#1242]
Hi,

While all other scans are working fine but for elb and alb i am getting error. And I have verified that role has full read access to ec2, loadbalancer, tag, etc.

```
2020-08-03 10:15:17,944 INFO: 'Problem Connecting to elb/Dev Account/xxx' [in /usr/local/lib/python3.6/dist-packages/security_monkey/exceptions.py:72]
INFO:security_monkey:'Problem Connecting to elb/Dev Account/xxxx'
2020-08-03 10:15:17,944 DEBUG: Logging exception from elb-watcher with location: ('elb', 'Dev Account', 'ap-south-1', 'xxxxx') to the database. [in /usr/local/lib/python3.6/dist-packages/security_monkey/datastore.py:750]
DEBUG:security_monkey:Logging exception from elb-watcher with location: ('elb', 'Dev Account', 'ap-south-1', 'xxx') to the database.
2020-08-03 10:15:17,970 DEBUG: Completed logging exception to database. [in /usr/local/lib/python3.6/dist-packages/security_monkey/datastore.py:781]
DEBUG:security_monkey:Completed logging exception to database.
``` 

after checking in DB there are 2 exceptions:-
1st  exception:-
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/security_monkey/decorators.py", line 95, in decorated_function
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/security_monkey/cloudaux_watcher.py", line 81, in invoke_get_method
    return self.get_method(item, **kwargs['conn_dict'])
  File "/usr/local/lib/python3.6/dist-packages/security_monkey/watchers/elb.py", line 28, in get_method
    result = get_load_balancer(item, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cloudaux/decorators.py", line 59, in decorated_function
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cloudaux/orchestration/aws/elb.py", line 184, in get_load_balancer
    return registry.build_out(flags, start_with=load_balancer, pass_datastructure=True, **conn)
  File "/usr/local/lib/python3.6/dist-packages/flagpole/__init__.py", line 295, in build_out
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/flagpole/__init__.py", line 250, in _do_method_pass
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/flagpole/__init__.py", line 203, in _execute_method
    retval = method(dict(result), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cloudaux/orchestration/aws/elb.py", line 141, in get_base
    if not isinstance(load_balancer['CreatedTime'], basestring):
NameError: name 'basestring' is not defined
```
2nd exception:- 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/security_monkey/decorators.py", line 95, in decorated_function
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/security_monkey/cloudaux_watcher.py", line 77, in invoke_list_method
    return self.list_method(**kwargs['conn_dict'])
  File "/usr/local/lib/python3.6/dist-packages/security_monkey/watchers/elb.py", line 25, in list_method
    return describe_load_balancers(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cloudaux/aws/decorators.py", line 67, in decorated_function
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cloudaux/aws/sts.py", line 204, in decorated_function
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cloudaux/aws/decorators.py", line 48, in decorated_function
    raise e
  File "/usr/local/lib/python3.6/dist-packages/cloudaux/aws/decorators.py", line 43, in decorated_function
    retval = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cloudaux/aws/elb.py", line 17, in describe_load_balancers
    return client.describe_load_balancers(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the DescribeLoadBalancers operation: The security token included in the request is invalid
```

I don't know which is causing which but other services are working so there shouldn't be an access problem at least.

**Comment by Deepak1100** [comment]
I think this is because of the python 3 upgrade.
for 1st exception, I have raised PR to Cloudaux.
https://github.com/Netflix-Skunkworks/cloudaux/pull/118/files

**Comment by mikegrima** [comment]
Thank you @Deepak1100 for reporting this and submitting the fix to CloudAux. I'm going to get this fixed for SM right now.

**Comment by mikegrima** [comment]
@Deepak1100 This should now be fixed. Please let me know if you still see issues.

**Comment by Deepak1100** [comment]
Thanks  @mikegrima 
it's working now.
