### ISSUE TITLE
monkey db upgrade - issues

### ISSUE THREAD

**Issue by ping4lucifer** [Netflix/security_monkey#1244]
## Please make sure that you have checked the boxes: 

- [x] [Pease review the Troubleshooting doc for additional details regarding your issue.](https://github.com/Netflix/security_monkey/blob/develop/docs/troubleshooting.md)
- [x] Review the [Quickstart guide](https://github.com/Netflix/security_monkey/blob/develop/docs/quickstart.md)
- [x] [Search for both open and closed issues](https://github.com/Netflix/security_monkey/issues?&q=is%3Aissue+) regarding the problem you are experiencing
- [x] **For permissions issues** (Access Denied and credential related errors), please refer to the requisite docs before submitting an issue:
[AWS](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_aws.md), [GCP](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_gcp.md), [OpenStack](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_openstack.md), [GitHub](https://github.com/Netflix/security_monkey/blob/develop/docs/github_setup.md#access-keys-and-permissions)

## Description of issue:
Dear Security_Monkey Team:

When running the monkey db upgrade after modifying the config.py file it throws the following error. Kindly assist.

(venv) ubuntu@ip-172-31-40-24:/usr/local/src/security_monkey$ monkey db upgrade
Traceback (most recent call last):
  File "/usr/local/src/security_monkey/venv/bin/monkey", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'deepdiff==4.0.9' distribution was not found and is required by security-monkey

**Comment by mikegrima** [comment]
Hello:

Did you install the requirements as documented here: https://github.com/Netflix/security_monkey/blob/develop/docs/installation/03-install-sm.md#clone-security_monkey ?

**Comment by ping4lucifer** [comment]
@mikegrima it worked like a charm. Thank you.

**Comment by priyanka-devops08** [comment]
I have followed all the mentioned steps but still I can see below error after running  **_monkey db upgrade_**:

/usr/local/src/security_monkey/venv/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py:835: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
Traceback (most recent call last):
  File "/usr/local/src/security_monkey/venv/bin/monkey", line 33, in <module>
    sys.exit(load_entry_point('security-monkey==1.1.1', 'console_scripts', 'monkey')())
  File "/usr/local/src/security_monkey/venv/bin/monkey", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/src/security_monkey/venv/lib/python3.5/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/src/security_monkey/venv/lib/python3.5/site-packages/security_monkey/__init__.py", line 188, in <module>
    from security_monkey.views.user_settings import UserSettings
  File "/usr/local/src/security_monkey/venv/lib/python3.5/site-packages/security_monkey/views/user_settings.py", line 15, in <module>
    from marshmallow.validate import OneOf
  File "/usr/local/src/security_monkey/venv/lib/python3.5/site-packages/marshmallow/__init__.py", line 16, in <module>
    from distutils.version import LooseVersion
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "/usr/local/src/security_monkey/venv/lib/python3.5/site-packages/_distutils_hack/__init__.py", line 82, in create_module
    return importlib.import_module('._distutils', 'setuptools')
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 981, in _gcd_import
  File "<frozen importlib._bootstrap>", line 931, in _sanity_check
SystemError: Parent module 'setuptools' not loaded, cannot perform relative import

**Comment by mikegrima** [comment]
Please re-run the installation steps from the venv.

**Comment by mikegrima** [comment]
I just did a fresh clone and doing the following documented installation instructions worked perfectly for me:
```cd security_monkey
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
python3 -m venv venv
source venv/bin/activate
pip install --upgrade setuptools
pip install --upgrade pip
pip install --upgrade urllib3[secure]   # to prevent InsecurePlatformWarning
pip install -r requirements.txt
pip install google-compute-engine  # Only required on GCP
pip install oauth2client # Required to retrieve GCP data
pip install google-api-python-client # Required to retrieve GCP data
pip install httplib2 # Required to retrieve GCP data
pip install cloudaux\[gcp\]
pip install cloudaux\[openstack\]    # Only required on OpenStack
pip install .
```
