### ISSUE TITLE
monkey db upgrade is throwing error

### ISSUE THREAD

**Issue by priyanka-devops08** [Netflix/security_monkey#1246]
Traceback (most recent call last):
  File "/usr/local/src/security_monkey/venv/bin/monkey", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'deepdiff==4.0.9' distribution was not found and is required by security-monkey

**Comment by mikegrima** [comment]
This issue was resolved in: https://github.com/Netflix/security_monkey/issues/1244
