### ISSUE TITLE
monkey db upgrade issue is still there

### ISSUE THREAD

**Issue by priyanka-devops08** [Netflix/security_monkey#1247]
Hi team,

monkey db upgrade issue:

I have followed all the mentioned steps in https://github.com/Netflix/security_monkey/issues/1244 , but still I can see below error after running monkey db upgrade:

/usr/local/src/security_monkey/venv/lib/python3.5/site-packages/flask_sqlalchemy/init.py:835: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future. Set it to True or False to suppress this warning.
'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
Traceback (most recent call last):
File "/usr/local/src/security_monkey/venv/bin/monkey", line 33, in
sys.exit(load_entry_point('security-monkey==1.1.1', 'console_scripts', 'monkey')())
File "/usr/local/src/security_monkey/venv/bin/monkey", line 25, in importlib_load_entry_point
return next(matches).load()
File "/usr/local/src/security_monkey/venv/lib/python3.5/site-packages/importlib_metadata/init.py", line 105, in load
module = import_module(match.group('module'))
File "/usr/lib/python3.5/importlib/init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 986, in _gcd_import
File "", line 969, in _find_and_load
File "", line 944, in _find_and_load_unlocked
File "", line 222, in _call_with_frames_removed
File "", line 986, in _gcd_import
File "", line 969, in _find_and_load
File "", line 958, in _find_and_load_unlocked
File "", line 673, in _load_unlocked
File "", line 665, in exec_module
File "", line 222, in _call_with_frames_removed
File "/usr/local/src/security_monkey/venv/lib/python3.5/site-packages/security_monkey/init.py", line 188, in
from security_monkey.views.user_settings import UserSettings
File "/usr/local/src/security_monkey/venv/lib/python3.5/site-packages/security_monkey/views/user_settings.py", line 15, in
from marshmallow.validate import OneOf
File "/usr/local/src/security_monkey/venv/lib/python3.5/site-packages/marshmallow/init.py", line 16, in
from distutils.version import LooseVersion
File "", line 969, in _find_and_load
File "", line 958, in _find_and_load_unlocked
File "", line 666, in _load_unlocked
File "", line 577, in module_from_spec
File "/usr/local/src/security_monkey/venv/lib/python3.5/site-packages/_distutils_hack/init.py", line 82, in create_module
return importlib.import_module('._distutils', 'setuptools')
File "/usr/lib/python3.5/importlib/init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 981, in _gcd_import
File "", line 931, in _sanity_check
SystemError: Parent module 'setuptools' not loaded, cannot perform relative import

**Comment by mikegrima** [comment]
Please use the other issue.
