### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'octodns' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by ConscriptMR** [Netflix/security_monkey#1255]
Traceback (most recent call last):
  File "/usr/local/bin/octodns-sync", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'octodns' distribution was not found and is required by the application

octodns install using: `pip install -r requirements.txt`
requirements contains: `-e git+https://git@github.com/github/octodns.git@07b8c19acc337efc90391f5024a346ce0956a5be#egg=octodns`
command ran was: octodns-sync --config-file=/etc/bind/octodns-config.yaml

**Comment by ConscriptMR** [comment]
sorry, wrong repo 😅
