### ISSUE TITLE
KeyError in ELB checks when using custom policies

### ISSUE THREAD

**Issue by bunjiboys** [Netflix/security_monkey#162]
When you use a custom policy on your ELB, it causes the elb watcher to throw a KeyError, see below for stacktrace

```
2015-07-06 23:01:02,013 ERROR: Job "run_change_reporter (trigger: interval[0:15:00], next run at: 2015-07-06 23:09:25.276738)" raised an exception [in build/bdist.linux-x86_64/egg/apscheduler/scheduler.py:520]
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/apscheduler/scheduler.py", line 512, in _run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/opt/security_monkey/security_monkey/scheduler.py", line 46, in run_change_reporter
    reporter.run(account, interval)
  File "/opt/security_monkey/security_monkey/reporter.py", line 56, in run
    (items, exception_map) = watcher.slurp()
  File "/opt/security_monkey/security_monkey/watchers/elb.py", line 191, in slurp
    'policies': [elb_policies[policy_name] for policy_name in li.policy_names]
KeyError: u'AWSConsole-SSLNegotiationPolicy-custom-policy-name'
```
Looking at the ELB the policy section contains the following:
```json
"Policies": {
    "LBCookieStickinessPolicies": [],
    "AppCookieStickinessPolicies": [],
    "OtherPolicies": [
        "AWSConsole-SSLNegotiationPolicy-custom-policy-name",
        "ELBSecurityPolicy-2015-05"
    ]
},
```
If i describe the policies for the ELB I see the policy fine, so I'm not sure why its causing a KeyError

**Comment by monkeysecurity** [comment]
I've seen these occasionally in the logs, but they seemed intermittent, so I had written it off as AWS API oddness.  Are you seeing this repeatedly?

If nothing else, we should verify that the exception is tracked in the exception map so it doesn't ruin the entire run of the ELB map.  After taking a quick peek, it looks like an exception here would prevent security_monkey from seeing any ELB changes and should be better handled.

**Comment by bunjiboys** [comment]
I do think it might be intermittent, but I do see these at a pretty regular cadence. And as you mentioned it does seem to kill the entire run which is what had me concerned the most, so I agree that if this is just API oddness, better exception handling would be a good compromise.

**Comment by DataSquid** [comment]
In 0.3.7 this is also an issue for a now-supported policy as well:

```2015-07-24 15:52:09,269 ERROR: Job "run_change_reporter (trigger: interval[0:15:00], next run at: 2015-07-24 16:06:03.041347)" raised an exception [in build/bdist.linux-x86_64/egg/apscheduler/scheduler.py:520]
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/apscheduler/scheduler.py", line 512, in _run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/src/security_monkey/security_monkey/scheduler.py", line 46, in run_change_reporter
    reporter.run(account, interval)
  File "/usr/local/src/security_monkey/security_monkey/reporter.py", line 56, in run
    (items, exception_map) = watcher.slurp()
  File "/usr/local/src/security_monkey/security_monkey/watchers/elb.py", line 191, in slurp
    'policies': [elb_policies[policy_name] for policy_name in li.policy_names]
KeyError: u'ELBSecurityPolicy-2015-05'```

**Comment by monkeysecurity** [comment]
A pull request is certainly welcome. 

I haven't had time to track this one down.
