### ISSUE TITLE
Problem Connecting to iamssl/Prd-NA/universal:\nlist index out of range

### ISSUE THREAD

**Issue by DataSquid** [Netflix/security_monkey#173]
This shows up in the logs of our 0.3.7 build:

```2015-07-24 15:53:08,406 INFO: Running IAM SSL for Prd-NA (15 minutes interval) [in /usr/local/src/security_monkey/security_monkey/reporter.py:55]
2015-07-24 15:53:08,640 WARNING: Traceback (most recent call last):
  File "/usr/local/src/security_monkey/security_monkey/watchers/iam/iam_ssl.py", line 159, in get_all_certs_in_region
    cert_info = get_cert_info(cert['body'])
  File "/usr/local/src/security_monkey/security_monkey/watchers/iam/iam_ssl.py", line 90, in get_cert_info
    'issuer': cert_get_issuer(cert),
  File "/usr/local/src/security_monkey/security_monkey/watchers/iam/iam_ssl.py", line 40, in cert_get_issuer
    return str(cert.get_issuer()).split("/O=")[1].split("/")[0].translate(None, " ,.").strip()
IndexError: list index out of range
 [in /usr/local/src/security_monkey/security_monkey/watchers/iam/iam_ssl.py:164]
2015-07-24 15:53:08,640 INFO: 'Problem Connecting to iamssl/Prd-NA/universal:\nlist index out of range' [in /usr/local/src/security_monkey/security_monkey/exceptions.py:68]
2015-07-24 15:53:08,640 INFO: Found 6 IAM SSLs from Prd-NA/universal [in /usr/local/src/security_monkey/security_monkey/watchers/iam/iam_ssl.py:168]```

**Comment by monkeysecurity** [comment]
Could you edit iam_ssl.py to have it print out `cert.get_issuer()` BEFORE the line where it does the splits?

CURRENT:

    def cert_get_issuer(cert):
        return str(cert.get_issuer()).split("/O=")[1].split("/")[0].translate(None, " ,.").strip()

NEW:

    def cert_get_issuer(cert):
        app.logger.debug("ISSUER: [{}]".format(cert.get_issuer()))
        return str(cert.get_issuer()).split("/O=")[1].split("/")[0].translate(None, " ,.").strip()

Then either manually run the iamssl watcher, or restart the scheduler.  Grep through the new logs for "ISSUER".

Your cert must not have `/O=` followed by a `/`

I guess we could put the current code in a try/except block, and simply return `cert.get_issuer()` if it runs into an exception parsing the issuer.

**Comment by DataSquid** [comment]
What's the correct procedure after I modify a .py?  It seem the .pyc isn't being recompiled if I just restart the scheduler; it always terminates quickly with a fatal error.

**Comment by monkeysecurity** [comment]
You probably introduced a syntax error when you edited the file.

Make sure you are using four spaces for indentation and not tabs.  The error message you're seeing should contain a hint to the error.

**Comment by DataSquid** [comment]
Ha, indeed I did, but I caught it a little to late, and posted a little too soon :)

```
2015-07-24 21:57:20,033 INFO: Running IAM SSL for d2l-staging (15 minutes interval) [in /usr/local/src/security_monkey/security_monkey/reporter.py:55]
2015-07-24 21:57:20,033 DEBUG: Checking iamssl/d2l-staging/us-east-1 [in /usr/local/src/security_monkey/security_monkey/watchers/iam/iam_ssl.py:133]
2015-07-24 21:57:20,149 DEBUG: ISSUER: [/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA] [in /usr/local/src/security_monkey/security_monkey/watchers/iam/iam_ssl.py:38]
2015-07-24 21:57:20,153 DEBUG: ISSUER: [/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA] [in /usr/local/src/security_monkey/security_monkey/watchers/iam/iam_ssl.py:38]
2015-07-24 21:57:20,176 DEBUG: ISSUER: [/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA] [in /usr/local/src/security_monkey/security_monkey/watchers/iam/iam_ssl.py:38]
2015-07-24 21:57:20,177 DEBUG: ISSUER: [/CN=RMQTESTCA] [in /usr/local/src/security_monkey/security_monkey/watchers/iam/iam_ssl.py:38]
2015-07-24 21:57:20,178 WARNING: Traceback (most recent call last):
  File "/usr/local/src/security_monkey/security_monkey/watchers/iam/iam_ssl.py", line 158, in get_all_certs_in_region
    cert_info = get_cert_info(cert['body'])
  File "/usr/local/src/security_monkey/security_monkey/watchers/iam/iam_ssl.py", line 89, in get_cert_info
    'issuer': cert_get_issuer(cert),
  File "/usr/local/src/security_monkey/security_monkey/watchers/iam/iam_ssl.py", line 39, in cert_get_issuer
    return str(cert.get_issuer()).split("/O=")[1].split("/")[0].translate(None, " ,.").strip()
IndexError: list index out of range
 [in /usr/local/src/security_monkey/security_monkey/watchers/iam/iam_ssl.py:163]
2015-07-24 21:57:20,178 INFO: 'Problem Connecting to iamssl/Prd-NA/universal:\nlist index out of range' [in /usr/local/src/security_monkey/security_monkey/exceptions.py:68]
2015-07-24 21:57:20,178 DEBUG: Adding ('iamssl', u'Prd-NA', 'universal') to the exceptions list. Exception was: 'Problem Connecting to iamssl/Prd-NA/universal:\nlist index out of range' [in /usr/local/src/security_monkey/security_monkey/watcher.py:153]
```

**Comment by monkeysecurity** [comment]
Ahh, so it's working for a few of your certs.  The one it's failing on (`/CN=RMQTESTCA`) doesn't have a proper issuer.  It must be a self-signed SSL cert.

I'll  add a try/except block. If it sees an exception, I'll just have it return "No Valid Issuer Found".
I'm about ready to head home today, so look for a fix early next week.

**Comment by DataSquid** [comment]
Have a good weekend.  Yes, it will be nice to have a quick way to audit use of self-signed certs in the env.  Thanks.

**Comment by monkeysecurity** [comment]
Hey @DataSquid 

I just pushed a new branch up to github:

https://github.com/Netflix/security_monkey/tree/feature/missing_certificate_issuer_issue_173

I'll do some testing this week and will update this issue once I've merged it to the develop branch.

**Comment by DataSquid** [comment]
It's been working well for me.

**Comment by monkeysecurity** [comment]
The feature has been merged to master.  55f09b29825931a453499e61cffe13b861270bfd

I'll delete the feature branch from github now.
