### ISSUE TITLE
build failure on Debian stable

### ISSUE THREAD

**Issue by pdbogen** [Netflix/security_monkey#312]
```
Traceback (most recent call last):
  File "setup.py", line 64, in <module>
    'jira==0.32'
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 393, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 617, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 668, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 716, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 631, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 874, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 886, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 636, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 666, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 856, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1078, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1063, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 68, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 114, in run
    return func()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 67, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 43, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-vU1im1/requests-2.2.1/setup.py", line 6, in <module>
    #
  File "/tmp/easy_install-vU1im1/requests-2.2.1/requests/__init__.py", line 53, in <module>
  File "/tmp/easy_install-vU1im1/requests-2.2.1/requests/packages/urllib3/contrib/pyopenssl.py", line 62, in <module>
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
```

This seems to be a result of pinning to requests 2.2.1, which uses a version of urllib3 that assumes SSLv3 is available. In modern versions of Debian, SSLv3 is not available in this way since it has known security vulnerabilities. Pinning requests to the latest (2.9.1) builds fine, though it remains to be seen if anything is broken when running by doing so.

**Comment by monkeysecurity** [comment]
Interesting.  FYI - the develop branch does not list requests as a requirement.  I feel pretty confident that I can remove the requirement from the master branch and not cause any problems.  Thanks for the report.  I'll push out an update in a minute and link to the commit here.

**Comment by monkeysecurity** [comment]
Hey @pdbogen - I removed requests from `setup.py` and `requirements.txt` in the master branch, which should fix it.

My master and development branches are diverging slightly, but I'll merge the two soon.
