### ISSUE TITLE
security_monkey should (at least offer an option to) not use logging.handlers.RotatingFileHandler

### ISSUE THREAD

**Issue by pdbogen** [Netflix/security_monkey#313]
Justification: I want to log to stdout / stderr (I'm running in Docker and these streams will be captured by my orchestration infrastructure); but RollingFileHandler tries and fails to seek on the "files" it logs to, leading to failures:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python2.7/logging/handlers.py", line 157, in shouldRollover
    self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
IOError: [Errno 29] Illegal seek
Logged from file scheduler.py, line 574
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python2.7/logging/handlers.py", line 157, in shouldRollover
    self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
IOError: [Errno 29] Illegal seek
Logged from file scheduler.py, line 579
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python2.7/logging/handlers.py", line 157, in shouldRollover
    self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
IOError: [Errno 29] Illegal seek
Logged from file scheduler.py, line 595
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python2.7/logging/handlers.py", line 157, in shouldRollover
    self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
IOError: [Errno 29] Illegal seek
Logged from file scheduler.py, line 606
INFO:apscheduler.scheduler:Scheduler has been shut down
```

I would expect that a regular FileHandler would work with /dev/stdout as the "file"; alternatively, a configuration option to simply log to stdout and/or stderr in lieu of file logging would address this for me.

**Comment by pdbogen** [comment]
n.b., reading the indicated line numbers in apscheduler/scheduler.py makes it clear that scheduler is operating nominally; starting, finding no jobs, and exiting. So this isn't a huge issue or anything, but I'd like ot be able to get valid logging nonetheless.

**Comment by monkeysecurity** [comment]
Hey @pdbogen - Any interest in supplying a pull request?  I agree with your solution and have seen this problem before.
