### ISSUE TITLE
python change finder sometimes throws exceptions

### ISSUE THREAD

**Issue by monkeysecurity** [Netflix/security_monkey#329]
Example:

```
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/apscheduler/scheduler.py", line 512, in _run_job
    retval = job.func(*job.args, **job.kwargs)
  File ".../securitymonkey/security_monkey/scheduler.py", line 48, in run_change_reporter
    reporter.run(account, interval)
  File ".../securitymonkey/security_monkey/reporter.py", line 57, in run
    watcher.find_changes(current=items, exception_map=exception_map)
  File ".../securitymonkey/security_monkey/watcher.py", line 293, in find_changes
    self.find_modified(previous=prev, current=current, exception_map=exception_map)
  File ".../securitymonkey/security_monkey/watcher.py", line 251, in find_modified
    if not sub_dict(prev_item.config) == sub_dict(curr_item.config):
  File "../securitymonkey/security_monkey/common/utils.py", line 51, in sub_dict
    for k in d:
TypeError: 'NoneType' object is not iterable
```

**Comment by monkeysecurity** [comment]
FYI - originally ran into this issue because I was tracking an AWS account where the security_monkey role lacked the `iam:ListAttachedRolePolicies` permission.

Check your logs for something like this to find any accounts lacking this permission: `assumed-role/SecurityMonkey/botor is not authorized to perform: iam:ListAttachedRolePolicies`
