### ISSUE TITLE
Installation Documentation Fix For Adding Amazon Accounts

### ISSUE THREAD

**Issue by kur3us** [Netflix/security_monkey#330]
In the Quick Start Guide, there is a section to add Amazon accounts.

The command it gives is:

`python manage.py amazon_accounts`

This results in a permissions error:

`Traceback (most recent call last):
  File "manage.py", line 18, in <module>
    from security_monkey import app, db
  File "/usr/local/src/security_monkey/security_monkey/__init__.py", line 45, in <module>
    handler = RotatingFileHandler(app.config.get('LOG_FILE'), maxBytes=10000000, backupCount=100)
  File "/usr/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 903, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 928, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/var/log/security_monkey/security_monkey-deploy.log'
`

If the command is changed to the following line, it works fine:

`sudo -E python manage.py amazon_accounts`

**Comment by monkeysecurity** [comment]
Good call.  The rest of the guide asks the user to `sudo -E`.

I'll see about pushing an update out tomorrow.
