### ISSUE TITLE
iam_ssl.py exception on elliptic curve

### ISSUE THREAD

**Issue by monkeysecurity** [Netflix/security_monkey#331]
```
Traceback (most recent call last):
  File "../securitymonkey/security_monkey/watchers/iam/iam_ssl.py", line 231, in get_all_certs_in_region
    cert_info = get_cert_info(cert['body'])
  File "../securitymonkey/security_monkey/watchers/iam/iam_ssl.py", line 161, in get_cert_info
    'size': cert_get_bitstrength(cert),
  File "../securitymonkey/security_monkey/watchers/iam/iam_ssl.py", line 43, in cert_get_bitstrength
    return cert.public_key().key_size
AttributeError: '_EllipticCurvePublicKey' object has no attribute 'key_size'
 [in ../securitymonkey/security_monkey/watchers/iam/iam_ssl.py:236]
```

Solution is probably to replace `cert_get_bitstrength(cert):` with this:

```
def cert_get_bitstrength(cert):
    """
    Calculates a certificates public key bit length.

    :param cert:
    :return: Integer
    """
    if hasattr(cert.public_key(), 'key_size'):
        return cert.public_key().key_size
    else:
        return None
```

**Comment by monkeysecurity** [comment]
Fixed in 7eba281f5bbd4f71ddebb9d4f5de8ef45fcd9084
