### ISSUE TITLE
Python exceptions  - AccessKey

### ISSUE THREAD

**Issue by subbu05** [Netflix/security_monkey#353]
After installing, configuring Secuirty Monkey I see following errors in security-monkey-deploy.log

2016-06-02 14:12:09,235 INFO: "Problem Connecting to iamrole/Staging/None:\n'AccessKeyId'" [in /usr/local/src/security_monkey/security_monkey/exceptions.py:68]
2016-06-02 14:12:09,235 ERROR: Job "run_change_reporter (trigger: interval[0:15:00], next run at: 2016-06-02 14:27:09.191017)" raised an exception [in build/bdist.linux-x86_64/egg/apscheduler/scheduler.py:520]
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/apscheduler/scheduler.py", line 512, in _run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/src/security_monkey/security_monkey/scheduler.py", line 48, in run_change_reporter
    reporter.run(account, interval)
  File "/usr/local/src/security_monkey/security_monkey/reporter.py", line 56, in run
    (items, exception_map) = watcher.slurp()
  File "/usr/local/src/security_monkey/security_monkey/watchers/iam/iam_role.py", line 103, in slurp
    return slurp_items()
  File "/usr/local/src/security_monkey/security_monkey/decorators.py", line 125, in decorated_function
    itm, exc = f(*args, **kwargs)
  File "/usr/local/src/security_monkey/security_monkey/watchers/iam/iam_role.py", line 91, in slurp_items
    [role['RoleName'] for role in roles],
TypeError: 'NoneType' object is not iterable

**Comment by alexandernilsson** [comment]
Looks like your instance fails to assume the SecurityMonkey rule. What does your trust relationship policy document for SecurityMonkeyInstanceProfile look like?

**Comment by monkeysecurity** [comment]
Hey @subbu05 - Haven't heard back from you.  I'm going to close the issue out.  Feel free to hop into the gitter chat room and someone should be able to help out:

https://gitter.im/Netflix/security_monkey

**Comment by subbu05** [comment]
Thanks you folks. I got it resolved with role updates.

**Comment by khushbuparakh** [comment]
Facing the same issue. what is the desired role? I am an editor right now.

**Comment by khushbuparakh** [comment]
@subbu05 what role you have used here. Is it like admin need to create service account ?
