### ISSUE TITLE
UndefinedError: 'flask_security.forms.LoginForm object' has no attribute 'generate_csrf_token'

### ISSUE THREAD

**Issue by mariusgrigaitis** [Netflix/security_monkey#494]
Latest pip installation does not result in working configuration on develop branch

Log from API:
```
secmonkey-api | 2017-01-10 16:00:44,931 ERROR: Exception on /login [GET] [in /usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py:1423]
secmonkey-api | Traceback (most recent call last):
secmonkey-api |   File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
secmonkey-api |     response = self.full_dispatch_request()
secmonkey-api |   File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
secmonkey-api |     rv = self.handle_user_exception(e)
secmonkey-api |   File "/usr/local/lib/python2.7/dist-packages/Flask_RESTful-0.3.3-py2.7.egg/flask_restful/__init__.py", line 270, in error_router
secmonkey-api |     return original_handler(e)
secmonkey-api |   File "/usr/local/lib/python2.7/dist-packages/Flask_RESTful-0.3.3-py2.7.egg/flask_restful/__init__.py", line 270, in error_router
secmonkey-api |     return original_handler(e)
secmonkey-api |   File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
secmonkey-api |     reraise(exc_type, exc_value, tb)
secmonkey-api |   File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
secmonkey-api |     rv = self.dispatch_request()
secmonkey-api |   File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
secmonkey-api |     return self.view_functions[rule.endpoint](**req.view_args)
secmonkey-api |   File "/usr/local/lib/python2.7/dist-packages/Flask_Security_Fork-1.8.2-py2.7.egg/flask_security/decorators.py", line 230, in wrapper
secmonkey-api |     return f(*args, **kwargs)
secmonkey-api |   File "/usr/local/lib/python2.7/dist-packages/Flask_Security_Fork-1.8.2-py2.7.egg/flask_security/views.py", line 88, in login
secmonkey-api |     **_ctx('login'))
secmonkey-api |   File "/usr/local/lib/python2.7/dist-packages/Flask_Security_Fork-1.8.2-py2.7.egg/flask_security/core.py", line 473, in render_template
secmonkey-api |     return render_template(*args, **kwargs)
secmonkey-api |   File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/templating.py", line 128, in render_template
secmonkey-api |     context, ctx.app)
secmonkey-api |   File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/templating.py", line 110, in _render
secmonkey-api |     rv = template.render(context)
secmonkey-api |   File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.9.4-py2.7.egg/jinja2/environment.py", line 1008, in render
secmonkey-api |     return self.environment.handle_exception(exc_info, True)
secmonkey-api |   File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.9.4-py2.7.egg/jinja2/environment.py", line 780, in handle_exception
secmonkey-api |     reraise(exc_type, exc_value, tb)
secmonkey-api |   File "/usr/local/src/security_monkey/security_monkey/templates/security/login_user.html", line 61, in top-level template code
secmonkey-api |     <input id="csrf_token" name="csrf_token" type="hidden" value="{{ login_user_form.generate_csrf_token() }}">
secmonkey-api | UndefinedError: 'flask_security.forms.LoginForm object' has no attribute 'generate_csrf_token'
```

I've investigated the issue a little:

security_monkey depends on Flask-Security-Fork: https://github.com/Netflix/security_monkey/blob/develop/setup.py#L33

Flask-Security-Fork depends on Flask-WTF>=0.13.1
https://github.com/inveniosoftware/flask-security-fork/blob/1.8.2/setup.py#L48

Flask-WTF installed is Flask-WTF==0.14.2

pip freeze:
```
APScheduler==2.1.2
Flask==0.10.1
Flask-Login==0.4.0
Flask-Mail==0.9.0
Flask-Migrate==1.3.1
Flask-Principal==0.4.0
Flask-RESTful==0.3.3
Flask-SQLAlchemy==1.0
Flask-Script==0.6.3
Flask-Security-Fork==1.8.2
Flask-WTF==0.14.2
Jinja2==2.9.4
Mako==1.0.6
MarkupSafe==0.23
PyJWT==1.4.2
PyYAML==3.11
Pygments==2.1.3
SQLAlchemy==0.9.2
Sphinx==1.2.2
WTForms==2.1
Werkzeug==0.11.15
alembic==0.8.9
aniso8601==1.2.0
argparse==1.2.1
bcrypt==3.1.2
blinker==1.4
boto==2.45.0
boto3==1.4.3
botocore==1.4.93
cffi==1.9.1
chardet==2.0.1
cloudaux==1.0.6
colorama==0.2.5
cryptography==1.7.1
docutils==0.13.1
dpath==1.3.2
enum34==1.1.6
futures==3.0.5
gunicorn==18.0
html5lib==0.999
idna==2.2
inflection==0.3.1
ipaddr==2.1.11
ipaddress==1.0.17
itsdangerous==0.23
jira==0.32
jmespath==0.9.0
joblib==0.10.3
oauthlib==2.0.1
passlib==1.7.0.post20170110153113
psycopg2==2.6.2
pyasn1==0.1.9
pycparser==2.17
pycurl==7.19.3
python-apt===0.9.3.5ubuntu2
python-dateutil==2.6.0
python-editor==1.0.3
pytz==2016.10
requests==2.2.1
requests-oauthlib==0.7.0
s3transfer==0.1.10
security-monkey==0.8.0
six==1.5.2
tlslite==0.4.9
urllib3==1.7.1
wheel==0.24.0
wsgiref==0.1.2
```

**Comment by monkeysecurity** [comment]
I've reproduced this bug.

yucky

**Comment by monkeysecurity** [comment]
`Flask-WTF` seems to have introduced the problem in 0.14.

It's working for me on 0.13.1.

```
pip uninstall Flask-WTF
pip install Flask-WTF==0.13.1
```

I'm not sure *what* in that change is causing the issue.  I'll poke around, but I may end up pinning to 0.13.1.

**Comment by monkeysecurity** [comment]
It looks like I can use Flask-WTF==0.14.1 if I make this change:

File "/usr/local/src/security_monkey/security_monkey/templates/security/login_user.html", line 61, in top-level template code
```
<input id="csrf_token" name="csrf_token" type="hidden" value="{{ login_user_form.generate_csrf_token() }}">
```
becomes
```
<input id="csrf_token" name="csrf_token" type="hidden" value="{{ login_user_form.csrf_token }}">
```

**Comment by monkeysecurity** [comment]
I'll push out a PR to PIN Flask-WTF to >= 0.14.1 and to update the four templates to stop using `generate_csrf_token()` and instead use `csrf_token`

**Comment by monkeysecurity** [comment]
Just merged a fix into develop.

**Comment by mariusgrigaitis** [comment]
I think we got something messed up.

Now I get:

```
{ "csrf_error": "The CSRF session token is missing." }
```

On login using email/password.

**Comment by mariusgrigaitis** [comment]
Looks like mistake on my part.

I was trying security monkey over http over docker. But config value for session cookie for docker environement is `SESSION_COOKIE_SECURE=True` and session does not get set for http.
