### ISSUE TITLE
IAM User UploadDate field JSON serialization error (Signing Certificate)

### ISSUE THREAD

**Issue by darkarnium** [Netflix/security_monkey#496]
Hey there,

When attempting to run `security_monkey` against one of our accounts, the following exception was encountered:

```
2016-12-23 19:43:35,980 ERROR: Database error processing accounts [u'Unicorns'], cleaning up session. [in /usr/local/src/security_monkey/security_monkey/scheduler.py:34]
Traceback (most recent call last):
  File "/usr/local/src/security_monkey/security_monkey/scheduler.py", line 32, in run_change_reporter
    reporter.run(account, interval)
  File "/usr/local/src/security_monkey/security_monkey/reporter.py", line 61, in run
    monitor.watcher.save()
  File "/usr/local/src/security_monkey/security_monkey/watcher.py", line 364, in save
    item.save(self.datastore)
  File "/usr/local/src/security_monkey/security_monkey/watcher.py", line 499, in save
    ephemeral=ephemeral)
  File "/usr/local/src/security_monkey/security_monkey/datastore.py", line 574, in store
    db.session.commit()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/scoping.py", line 149, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 765, in commit
    self.transaction.commit()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 370, in commit
    self._prepare_impl()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 350, in _prepare_impl
    self.session.flush()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 1879, in flush
    self._flush(objects)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 1997, in _flush
    transaction.rollback(_capture_exception=True)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/langhelpers.py", line 57, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 1961, in _flush
    flush_context.execute()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/unitofwork.py", line 370, in execute
    rec.execute(self)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/unitofwork.py", line 523, in execute
    uow
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/persistence.py", line 64, in save_obj
    mapper, table, insert)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/persistence.py", line 594, in _emit_insert_statements
    execute(statement, params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 717, in execute
    return meth(self, multiparams, params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/elements.py", line 317, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 814, in _execute_clauseelement
    compiled_sql, distilled_params
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 881, in _execute_context
    None, None)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1076, in _handle_dbapi_exception
    exc_info
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 185, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 877, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 574, in _init_compiled
    processors[key](compiled_params[key])
  File "build/bdist.linux-x86_64/egg/sqlalchemy/dialects/postgresql/json.py", line 181, in process
    return json_serializer(value).encode(encoding)
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
StatementError: datetime.datetime(2014, 3, 18, 0, 56, 26, tzinfo=tzlocal()) is not JSON serializable (original cause: TypeError: datetime.datetime(2014, 3, 18, 0, 56, 26, tzinfo=tzlocal()) is not JSON serializable) u'INSERT INTO itemrevision (active, config, date_created, date_last_ephemeral_change, item_id) VALUES (%(active)s, %(config)s, %(date_created)s, %(date_last_ephemeral_change)s, %(item_id)s) RETURNING itemrevision.id' [{'active': True, 'date_last_ephemeral_change': None, 'config': {u'UserName': 'test.user@example.org', 'AccessKeys': [{u'UserName': 'test.user@example.org', u'Status': 'Active', u'CreateDate': '2015-07-22 05:16:11+00:00', u'AccessKeyId': 'AKIAXXXXXXXXXXXXXXX', u'ServiceName': 'ec2', u'LastUsedDate': '2016-12-16 21:32:00+00:00', u'Region': 'us-east-1'}], u'PasswordLastUsed': '2016-12-16 21:02:37+00:00', 'SigningCertificates': {'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA': {u'UserName': 'test.user@example.org', u'Status': 'Active', u'CertificateBody': '-----BEGIN CERTIFICATE-----TOTALLY_NOT_AN_SSL_CERTIFICATE-----END CERTIFICATE-----', u'CertificateId': 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', u'UploadDate': datetime.datetime(2014, 3, 18, 0, 56, 26, tzinfo=tzlocal())}}, u'CreateDate': '2014-03-17 22:00:38+00:00', 'InlinePolicies': {}, u'UserId': 'AIDAYYYYYYYYYYYYYYYYY', '_version': 1, 'ManagedPolicies': [], 'MfaDevices': {'arn:aws:iam::ACCOUNTID:mfa/test.user@example.org': {u'UserName': 'test.user@example.org', u'SerialNumber': 'arn:aws:iam::ACCOUNTID:mfa/test.user@example.org', u'EnableDate': '2015-09-24 13:04:12+00:00'}}, 'LoginProfile': {u'UserName': 'test.user@example.org', u'CreateDate': '2014-03-17 22:04:53+00:00', u'PasswordResetRequired': False}, u'Path': '/', u'Arn': 'arn:aws:iam::ACCOUNTID:user/test.user@example.org'}, 'item_id': 5433}]
2016-12-23 19:43:36,015 DEBUG: Logging exception from scheduler-run-change-reporter with location: None to the database. [in /usr/local/src/security_monkey/security_monkey/datastore.py:636]
2016-12-23 19:43:36,025 DEBUG: Completed logging exception to database. [in /usr/local/src/security_monkey/security_monkey/datastore.py:668]
2016-12-23 19:43:36,045 INFO: Job "run_change_reporter (trigger: interval[0:15:00], next run at: 2016-12-23 19:44:50.576187)" executed successfully [in build/bdist.linux-x86_64/egg/apscheduler/scheduler.py:527]
```

This issue was encountered in a deployment using https://github.com/Netflix/security_monkey/commit/ff0517cab6da3e3b4afc708eddab846346ea89ee of security_monkey.

Digging deeper this appears to be due to the way in which `cloudaux` is returning data to be stored by security_monkey. I have managed to patch this in `cloudaux` with an addition to `cloudaux/aws/iam.py` and a PR has been raised to the project in order to ensure this datetime object is properly cast to a string.

After forking and patching `cloudaux` I have confirmed that a fresh install of security_monkey no longer encounters this issue (using the bumped / patched version of `cloudaux` from my fork). A PR has been raised at Netflix-Skunkworks/cloudaux#14 and this issue has been opened for visibility.

Cheers,
Peter

**Comment by monkeysecurity** [comment]
Thanks a bunch for the PR.

I'll push the new cloudaux version to pypi tomorrow and update the security_monkey setup.py to depend on the new version.

I'll leave this open until then.
