### ISSUE TITLE
Error 500 when trying to create account with expired session

### ISSUE THREAD

**Issue by redixin** [Netflix/security_monkey#498]
Full traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "/usr/local/lib/python2.7/dist-packages/Flask_WTF-0.14.2-py2.7.egg/flask_wtf/csrf.py", line 221, in csrf_protect
    self.protect()
  File "/usr/local/lib/python2.7/dist-packages/Flask_WTF-0.14.2-py2.7.egg/flask_wtf/csrf.py", line 252, in protect
    self._error_response(e.args[0])
  File "/usr/local/lib/python2.7/dist-packages/Flask_WTF-0.14.2-py2.7.egg/flask_wtf/csrf.py", line 324, in handler
    response = current_app.make_response(view(reason))
  File "/home/ubuntu/security_monkey/security_monkey/__init__.py", line 55, in csrf_error
    return render_template('csrf_error.json', reason=reason), 400
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/templating.py", line 126, in render_template
    ctx.app.update_template_context(context)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 716, in update_template_context
    context.update(func())
  File "/usr/local/lib/python2.7/dist-packages/Flask_Login-0.4.0-py2.7.egg/flask_login/utils.py", line 335, in _user_context_processor
    return dict(current_user=_get_user())
  File "/usr/local/lib/python2.7/dist-packages/Flask_Login-0.4.0-py2.7.egg/flask_login/utils.py", line 302, in _get_user
    current_app.login_manager._load_user()
  File "/usr/local/lib/python2.7/dist-packages/Flask_Login-0.4.0-py2.7.egg/flask_login/login_manager.py", line 313, in _load_user
    return self._load_from_request(request)
  File "/usr/local/lib/python2.7/dist-packages/Flask_Login-0.4.0-py2.7.egg/flask_login/login_manager.py", line 370, in _load_from_request
    user = self.request_callback(request)
  File "/usr/local/lib/python2.7/dist-packages/Flask_Security_Fork-1.8.2-py2.7.egg/flask_security/core.py", line 215, in _request_loader
    token = request.json.get(args_key, token)
AttributeError: 'unicode' object has no attribute 'get'
```

**Comment by redixin** [comment]
This happened because request body contain double encoded json object.

**Comment by monkeysecurity** [comment]
With expired session?

**Comment by redixin** [comment]
When session in your browser is expired.

**Comment by redixin** [comment]
Steps to reproduce:

1. Log into account
2. Go to settings and open "create account" page
3. Fill in form and delete cookies in your browser
4. Submit form
