### ISSUE TITLE
Latest Docker setup not pulling data - Credentials issue

### ISSUE THREAD

**Issue by cplvic** [Netflix/security_monkey#584]
HI I setup a pilot a few months back following the docker instructions and every worked including accessing a second account. However I ran the setup again on another beefier instance again using docker and the scheduler wont pull anything. 

I ran a packet capture and after the scheduler restarts I keep seeing 404 errors for 169.254.169.254/latest/meta-data/iam/security-credentials/

I double checked the role, the policy, the user and trust and it seems to be good.

Help?

**Comment by cplvic** [comment]
these are the log snippets from the the scheduler container /var/log/security_monkey/security_monkey-deploy.log  

2017-03-04 00:49:04,331 DEBUG: Adding ('rds', u'MY VPC', u'us-west-2') to the exceptions list. Exception was: "Problem Connecting to rds/MY VPC/us-west-2:\nNo handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials" [in /usr/local/src/security_monkey/security_monkey/watcher.py:145]
2017-03-04 00:49:04,331 DEBUG: Checking rds/MY VPC/us-gov-west-1 [in /usr/local/src/security_monkey/security_monkey/watchers/rds_security_group.py:53]
2017-03-04 00:49:04,334 DEBUG: Checking rds/MY VPC/us-west-1 [in /usr/local/src/security_monkey/security_monkey/watchers/rds_security_group.py:53]
2017-03-04 00:49:04,336 INFO: "Problem Connecting to rds/MY VPC/us-west-1:\nNo handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials" [in /usr/local/src/security_monkey/security_monkey/exceptions.py:68]
2017-03-04 00:49:04,336 DEBUG: Adding ('rds', u'MY VPC', u'us-west-1') to the exceptions list. Exception was: "Problem Connecting to rds/MY VPC/us-west-1:\nNo handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials" [in /usr/local/src/security_monkey/security_monkey/watcher.py:145]
2017-03-04 00:49:04,336 DEBUG: Checking rds/MY VPC/eu-central-1 [in /usr/local/src/security_monkey/security_monkey/watchers/rds_security_group.py:53]2017-03-04 00:49:04,339 INFO: "Problem Connecting to rds/MY VPC/eu-central-1:\nNo handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials" [in /usr/local/src/security_monkey/security_monkey/exceptions.py:68]
2017-03-04 00:49:04,339 DEBUG: Adding ('rds', u'MY VPC', u'eu-central-1') to the exceptions list. Exception was: "Problem Connecting to rds/MY VPC/eu-central-1:\nNo handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials" [in /usr/local/src/security_monkey/security_monkey/watcher.py:145]
2017-03-04 00:49:04,339 DEBUG: Checking rds/MY VPC/sa-east-1 [in /usr/local/src/security_monkey/security_monkey/watchers/rds_security_group.py:53]
st-1:\nNo handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials" [in /usr/local/src/security_monkey/security_monkey/exceptions.py:68]
2017-03-04 00:49:04,342 DEBUG: Adding ('rds', u'MY VPC', u'sa-east-1') to the exceptions list. Exception was: "Problem Connecting to rds/MY VPC/sa-east-1:\nNo handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials" [in /usr/local/src/security_monkey/security_monkey/watcher.py:145]
2017-03-04 00:49:04,344 DEBUG:

Saving Issues. [in /usr/local/src/security_monkey/security_monkey/auditor.py:142]
2017-03-04 00:49:04,344 DEBUG: Creating/Assigning Auditor Settings in account [u'MY VPC'] and tech rds [in /usr/local/src/security_monkey/security_monkey/auditor.py:221]
2017-03-04 00:49:04,346 DEBUG: Done Creating/Assigning Auditor Settings in account [u'MY VPC'] and tech rds [in /usr/local/src/security_monkey/security_monkey/auditor.py:233]
2017-03-04 00:49:04,346 INFO: 0 deleted RDS Security Groups in [u'MY VPC'] [in /usr/local/src/security_monkey/security_monkey/watcher.py:307]
2017-03-04 00:49:04,346 INFO: 0 created RDS Security Groups in [u'MY VPC'] [in /usr/local/src/security_monkey/security_monkey/watcher.py:308]
VPC'] [in /usr/local/src/security_monkey/security_monkey/watcher.py:309]ny CORP --More--(95%)
2017-03-04 00:49:04,347 INFO: Account MY VPC is done with RDS Security Group [in /usr/local/src/security_monkey/security_monkey/reporter.py:66]
2017-03-04 00:49:04,350 ERROR: Job "run_change_reporter (trigger: interval[0:15:00], next run at: 2017-03-04 01:04:04.090999)" raised an exception [in build/bdist.linux-x86_64/egg/apscheduler/scheduler.py:520]
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/apscheduler/scheduler.py", line 512, in _run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/src/security_monkey/security_monkey/scheduler.py", line 44, in run_change_reporter
    reporter.run(account)
  File "/usr/local/src/security_monkey/security_monkey/reporter.py", line 55, in run
    (items, exception_map) = watcher.slurp()
  File "/usr/local/src/security_monkey/security_monkey/watchers/elb.py", line 120, in slurp
    self._setup_botocore(account)
  File "/usr/local/src/security_monkey/security_monkey/watchers/elb.py", line 79, in _setup_botocore
    self.botocore_session = connect(account, 'botocore')
ine 56, in connect/src/security_monkey/security_monkey/common/sts_connect.py", l--More--(97%)
    sts = boto.connect_sts()
  File "/usr/local/lib/python2.7/dist-packages/boto-2.34.0-py2.7.egg/boto/__init__.py", line 578, in connect_sts
    return STSConnection(aws_access_key_id, aws_secret_access_key, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/boto-2.34.0-py2.7.egg/boto/sts/connection.py", line 89, in __init__
    profile_name=profile_name)
  File "/usr/local/lib/python2.7/dist-packages/boto-2.34.0-py2.7.egg/boto/connection.py", line 1096, in __init__
    profile_name=profile_name)
  File "/usr/local/lib/python2.7/dist-packages/boto-2.34.0-py2.7.egg/boto/connection.py", line 569, in __init__
    host, config, self.provider, self._required_auth_capability())
  File "/usr/local/lib/python2.7/dist-packages/boto-2.34.0-py2.7.egg/boto/auth.py", line 975, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials

**Comment by cplvic** [comment]
I did check time on the docker containers. It is all aligned.

**Comment by mikegrima** [comment]
Hello @cplvic : If you are running this on a Docker container, access to the metadata service will fail.

You will need to use static keys in that case (or have some custom solution to Docker that is able to pass creds through a mocked metadata service)

**Comment by cplvic** [comment]
I created the boto.cfg file and added in the access and secret keys.
Is that correct?

**Comment by mikegrima** [comment]
Where did you place `boto.cfg`?

**Comment by cplvic** [comment]
the boto.cfg was placed in the same directory when I installed the api container.
It ultimately ended up in the api container /etc/boto.cfg

oddly I cannot access that file as the permissions are all ganked as ????

**Comment by cplvic** [comment]
like this
lrwxrwxrwx.  1 root root      15 Feb 12  2015 blkid.tab -> /dev/.blkid.tab
???????????  ? ?    ?          ?            ? boto.cfg
drwxr-xr-x.  3 root root      21 Feb 23  2015 ca-certificates
-rw-r--r--.  1 root root    7464 Feb 23  2015 ca-certificates.conf

**Comment by mikegrima** [comment]
Yeah, that would cause issues.  Can you `chown` it to `root:root` and `chmod 750` it?

**Comment by cplvic** [comment]
i cant. I have to delete the container first. I can verify when it transfers over for the host, the permissions are 755 and owned by root BUT some process munges it.
 I even manually recreated the file but it still happens/  Where are the credentials stored other than on the api server?

**Comment by mikegrima** [comment]
Per the boto docs: http://boto3.readthedocs.io/en/latest/guide/configuration.html#boto2-config, you can place it anywhere it expect it.

However, there appear to be other factors affecting your container. Are you copying the file in with your `Dockerfile`, mounting it in, generating it dynamically, or something else?

**Comment by cplvic** [comment]
Hye Mike I'm not doing anything special. Just running the command but I found something interesting. Looks like the boto.cfg and hosts file are not really simple files?

root@f7e728de76ef:/etc# df -h
Filesystem                                                                                           Size  Used Avail Use% Mounted on
/dev/mapper/docker-253:0-135049326-61304c79aa096cf607a028f58fedd6077685fe3ca6f29327bfbf51fd0bb09beb   10G  655M  9.4G   7% /
tmpfs                                                                                                3.9G     0  3.9G   0% /dev
tmpfs                                                                                                3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/mapper/centos-root                                                                               36G  4.3G   32G  12% /etc/boto.cfg
/dev/mapper/centos-root                                                                               36G  4.3G   32G  12% /etc/hosts
shm                                                                                                   64M     0   64M   0% /dev/shm
tmpfs                                                                                                3.9G     0  3.9G   0% /proc/kcore
tmpfs                                                                                                3.9G     0  3.9G   0% /proc/timer_list
tmpfs                                                                                                3.9G     0  3.9G   0% /proc/timer_stats
tmpfs                                                                                                3.9G     0  3.9G   0% /proc/sched_debug

**Comment by mikegrima** [comment]
It looks like you have it mounted to some odd thing.  What are you doing in your Dockerfile?

**Comment by cplvic** [comment]
Okedoke. When I look at the instructions here https://github.com/Netflix-Skunkworks/zerotodocker/wiki/Security-Monkey

There are two commands that use the "-v `pwd`/boto.cfg:/etc/boto.cfg:ro"
Installing security_monkey-api and security_monkey-scheduler

Following those steps results in the the boto.cfg mounting like what I saw above with no way to adjust the file. I ran the commands without the "-v ..." and I logged into each container to manually create the file. 
Security Monkey now populates! Weird.... but thanks for your feedback as it got me looking at the right stuff.

**Comment by mikegrima** [comment]
Hmm.  Surprised you are seeing that. I normally use the `-v` option on my docker images without issues.

Does:
```
`pwd`/boto.cfg
```
properly point to your `boto.cfg` file? It is better to have this mounted in vs. baked in, and would prefer you take that direction.

**Comment by cplvic** [comment]
Thanks MIke

**Comment by mikegrima** [comment]
Hello @cplvic -- going to close this out. 

Please reach out to us on Gitter if you have any additional issues.
