### ISSUE TITLE
Unable to edit or add Accounts on develop branch

### ISSUE THREAD

**Issue by ironroot** [Netflix/security_monkey#628]
Hi

during my testing I tried the develop branch and when I go to edit or add a new AWS account it go to a blank page with Loading on it, I see no errors in any of the logs but I do see the following javascript error. Any help would be great thanks all

`NullError: method not found: 'ga2' on null

STACKTRACE:
TypeError: Cannot read property 'ga2' of undefined
    at Object.J.a1 (https://192.168.99.100/main.dart.js:49386:32)
    at bs.dart.bs.GP (https://192.168.99.100/main.dart.js:46574:9)
    at qI.dart.qI.$2 (https://192.168.99.100/main.dart.js:46600:33)
    at HN.A (https://192.168.99.100/main.dart.js:29022:15)
    at Object.J.am (https://192.168.99.100/main.dart.js:49327:35)
    at bs.FK (https://192.168.99.100/main.dart.js:46584:35)
    at Object.dart.bs.t.aia (https://192.168.99.100/main.dart.js:46598:3)
    at Dr.dart.ao6 (https://192.168.99.100/main.dart.js:46626:27)
    at Dr.dart.adv.func (https://192.168.99.100/main.dart.js:26755:24)
    at qr.dart.qr.DD.func [as DD] (https://192.168.99.100/main.dart.js:27847:12)`

**Comment by monkeysecurity** [comment]
Did you compile the dart in the develop branch or are you using the static.tar.gz in the last release?

**Comment by ironroot** [comment]
I did not compile the dart, I will give that a try thank you

**Comment by ironroot** [comment]
Found the issue thanks
