### ISSUE TITLE
Looking for aws_accounts.json in the wrong location

### ISSUE THREAD

**Issue by AlexCline** [Netflix/security_monkey#672]
When running `monkey aws_accounts` in an installation of v0.9.0, I get the following error:

```
monkey amazon_accounts
2017-04-14 22:49:00,813 INFO: Started thread pool with 5 core threads and 25 maximum threads [in build/bdist.linux-x86_64/egg/apscheduler/threadpool.py:52]
Traceback (most recent call last):
  File "/usr/local/bin/monkey", line 9, in <module>
    load_entry_point('security-monkey==0.9.0', 'console_scripts', 'monkey')()
  File "/usr/local/lib/python2.7/dist-packages/security_monkey-0.9.0-py2.7.egg/security_monkey/manage.py", line 625, in main
    manager.run()
  File "/usr/local/lib/python2.7/dist-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/__init__.py", line 397, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/__init__.py", line 376, in handle
    return handle(app, *positional_args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/commands.py", line 145, in handle
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/security_monkey-0.9.0-py2.7.egg/security_monkey/manage.py", line 152, in amazon_accounts
    data = json.load(open(data_file, 'r'))
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/security_monkey-0.9.0-py2.7.egg/security_monkey/data/aws_accounts.json'
```

The `aws_accounts.json` file exists in the SM root directory `/usr/local/src/security_monkey`. Copying this file to the path in the error message gets rid of the error.

**Comment by monkeysecurity** [comment]
`aws_accounts.json` actually exists in `/usr/local/src/security_monkey/data`, does it not?

https://github.com/Netflix/security_monkey/tree/develop/data

#673 created to fix.

**Comment by AlexCline** [comment]
You're correct, the aws_accounts.json file exists in the data directory under the SM root.
