### ISSUE TITLE
Missing Jinja template in v0.9.0

### ISSUE THREAD

**Issue by AlexCline** [Netflix/security_monkey#674]
When running `monkey start_scheduler`, the following error message is thrown when trying to send change emails:

```
2017-04-15 11:23:11,636 INFO: Alerter: Found some changes in branders: rdssnapshot [in /usr/local/lib/python2.7/dist-packages/security_monkey-0.9.0-py2.7.egg/security_monkey/alerter.py:92]
2017-04-15 11:23:11,642 ERROR: Job "run_change_reporter (trigger: interval[1:00:00], next run at: 2017-04-15 12:06:22.097601)" raised an exception [in build/bdist.linux-x86_64/egg/apscheduler/scheduler.py:520]
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/apscheduler/scheduler.py", line 512, in _run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/security_monkey-0.9.0-py2.7.egg/security_monkey/scheduler.py", line 32, in run_change_reporter
    reporter.run(account, interval)
  File "/usr/local/lib/python2.7/dist-packages/security_monkey-0.9.0-py2.7.egg/security_monkey/reporter.py", line 87, in run
    self.account_alerter.report()
  File "/usr/local/lib/python2.7/dist-packages/security_monkey-0.9.0-py2.7.egg/security_monkey/alerter.py", line 94, in report
    body = report_content(content)
  File "/usr/local/lib/python2.7/dist-packages/security_monkey-0.9.0-py2.7.egg/security_monkey/alerter.py", line 42, in report_content
    template = jenv.get_template('jinja_change_email.html')
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.9.6-py2.7.egg/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.9.6-py2.7.egg/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.9.6-py2.7.egg/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.9.6-py2.7.egg/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: jinja_change_email.html
```

The jinja templates exist in `/usr/local/src/security_monkey/security_monkey/templates/jinja_change_email.html`. They do not exist in `/usr/local/lib/python2.7/dist-packages/security_monkey-0.9.0-py2.7.egg/security_monkey` which is where I believe the alerter is looking for the templates.

Might this be related to #672 and #673?

Because of this error, I'm not receiving change alert emails from Security Monkey.

**Comment by AlexCline** [comment]
I was able to patch this error (and #672) by adding the following to my Dockerfile, symlinking the needed directories into the package location:

```
cd /usr/local/lib/python2.7/dist-packages/security_monkey-0.9.0-py2.7.egg/security_monkey
ln -s /usr/local/src/security_monkey/data .
ln -s /usr/local/src/security_monkey/security_monkey/templates/ .
```

Obviously this is a hack.

**Comment by monkeysecurity** [comment]
Short term solution appears to be to use `python setup.py develop` instead of `python setup.py install`.

I'm reading up on setuptools to try and figure this out.

**Comment by monkeysecurity** [comment]
Section 2.6 and 2.7 seem relevant: https://docs.python.org/2/distutils/setupscript.html#installing-package-data

**Comment by monkeysecurity** [comment]
Adding this to `setup.py` seems to ensure the templates are included:

```
package_data={
        'security_monkey': [
            'templates/*.json',
            'templates/*.html',
            'templates/security/*.html',
        ]
    },
```
