### ISSUE TITLE
NameError: global name 'select_autoescape' is not defined

### ISSUE THREAD

**Issue by kpcyrd** [Netflix/security_monkey#703]
After the upgrade to security monkey 0.9.1 I've noticed this exception in the logs. This happens in docker but might not be limited to the docker image.

```
Apr 26 19:52:31 worker docker[3017]: 2017-04-26 19:52:31,915 DEBUG: Logging exception from scheduler-change-reporter-uncaught with location: None to the database. [in /usr/local/lib/python2.7/dist-packages/security_monkey-0.9.1-py2.7.egg/security_monkey/datastore.py:696]
Apr 26 19:52:31 worker docker[3017]: 2017-04-26 19:52:31,920 DEBUG: Completed logging exception to database. [in /usr/local/lib/python2.7/dist-packages/security_monkey-0.9.1-py2.7.egg/security_monkey/datastore.py:727]
Apr 26 19:52:31 worker docker[3017]: 2017-04-26 19:52:31,920 ERROR: Job "run_change_reporter (trigger: interval[1:00:00], next run at: 2017-04-26 20:46:19.111281)" raised an exception [in build/bdist.linux-x86_64/egg/apscheduler/scheduler.py:520]
Apr 26 19:52:31 worker docker[3017]: Traceback (most recent call last):
Apr 26 19:52:31 worker docker[3017]:   File "build/bdist.linux-x86_64/egg/apscheduler/scheduler.py", line 512, in _run_job
Apr 26 19:52:31 worker docker[3017]:     retval = job.func(*job.args, **job.kwargs)
Apr 26 19:52:31 worker docker[3017]:   File "/usr/local/lib/python2.7/dist-packages/security_monkey-0.9.1-py2.7.egg/security_monkey/scheduler.py", line 32, in run_change_reporter
Apr 26 19:52:31 worker docker[3017]:     reporter.run(account, interval)
Apr 26 19:52:31 worker docker[3017]:   File "/usr/local/lib/python2.7/dist-packages/security_monkey-0.9.1-py2.7.egg/security_monkey/reporter.py", line 87, in run
Apr 26 19:52:31 worker docker[3017]:     self.account_alerter.report()
Apr 26 19:52:31 worker docker[3017]:   File "/usr/local/lib/python2.7/dist-packages/security_monkey-0.9.1-py2.7.egg/security_monkey/alerter.py", line 94, in report
Apr 26 19:52:31 worker docker[3017]:     body = report_content(content)
Apr 26 19:52:31 worker docker[3017]:   File "/usr/local/lib/python2.7/dist-packages/security_monkey-0.9.1-py2.7.egg/security_monkey/alerter.py", line 41, in report_content
Apr 26 19:52:31 worker docker[3017]:     jenv = get_jinja_env()
Apr 26 19:52:31 worker docker[3017]:   File "/usr/local/lib/python2.7/dist-packages/security_monkey-0.9.1-py2.7.egg/security_monkey/common/jinja.py", line 35, in get_jinja_env
Apr 26 19:52:31 worker docker[3017]:     autoescape=select_autoescape(['html', 'xml']))
Apr 26 19:52:31 worker docker[3017]: NameError: global name 'select_autoescape' is not defined
```

**Comment by monkeysecurity** [comment]
Hey @kpcyrd 
We're working on a fix.  Should be out shortly.

**Comment by monkeysecurity** [comment]
#697 should fix

**Comment by monkeysecurity** [comment]
#697 merged so closing this ticket.
