### ISSUE TITLE
No audit issues in security monkey v0.8.

### ISSUE THREAD

**Issue by RobertNorthard** [Netflix/security_monkey#710]
We are not able to see any audit issues in the security monkey dashboard. Looking at the logs we are getting the following exception.

```
2017-04-27 16:39:53,599 DEBUG: Logging exception from scheduler-change-reporter-uncaught with location: None to the database. [in /usr/local/src/security_monkey/security_monkey/datastore.py:636]
2017-04-27 16:39:53,602 DEBUG: Completed logging exception to database. [in /usr/local/src/security_monkey/security_monkey/datastore.py:668]
2017-04-27 16:39:53,602 ERROR: Job "run_change_reporter (trigger: interval[0:15:00], next run at: 2017-04-27 16:47:53.818240)" raised an exception [in build/bdist.linux-x86_64/egg/apscheduler/scheduler.py:520]
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/apscheduler/scheduler.py", line 512, in _run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/src/security_monkey/security_monkey/scheduler.py", line 32, in run_change_reporter
    reporter.run(account, interval)
  File "/usr/local/src/security_monkey/security_monkey/reporter.py", line 53, in run
    unique_watcher_results = self.slurp_unique_watchers(mons, account, interval)
  File "/usr/local/src/security_monkey/security_monkey/reporter.py", line 97, in slurp_unique_watchers
    (items, exception_map) = monitor.watcher.slurp()
TypeError: 'NoneType' object is not iterable
```

Please can you provide guidance on how to debug this further.

**Comment by idando1** [comment]
did you mange to solve this ?

**Comment by finalriposte** [comment]
Interesting I have a similar thing with 0.9.1.
Steps taken:
At the CLI assume role and get creds.
Use aws cli to check system calls, passed (instances reported back to command line).
supervisorctl start securitymonkey securitymonkeyscheduler
(tcpdump running in background)
Can see lots of traffic, I get the error:
    reporter.run(account, interval)
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/security_monkey-0.9.1-py2.7.egg/security_monkey/reporter.py", line 56, in run
    (items, exception_map) = monitor.watcher.slurp()
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/security_monkey-0.9.1-py2.7.egg/security_monkey/watchers/s3.py", line 79, in slurp
    return slurp_items()
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/security_monkey-0.9.1-py2.7.egg/security_monkey/decorators.py", line 151, in decorated_function
    itm, exc = f(*args, **kwargs)
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/security_monkey-0.9.1-py2.7.egg/security_monkey/watchers/s3.py", line 68, in slurp_items
    for bucket_name in bucket_names:
TypeError: 'NoneType' object is not iterable


I am going to get a hold of the proxy logs to check the response codes.
(SecurityMonkey in this environment requires proxy access)

**Comment by mikegrima** [comment]
@RobertNorthard ,and @finalriposte : Is this still an issue?

**Comment by mikegrima** [comment]
@finalriposte : The `NoneType` issue IIRC is related to the Security Monkey user not having access to that bucket (perhaps a `deny` policy on the bucket)?  It's a bug that we still need to fix (did we fix this yet @monkeysecurity ?).
