### ISSUE TITLE
IntegrityError: (IntegrityError) duplicate key value violates unique constraint "ix_item_arn" when adding GCP projects with the same Firewall rule name

### ISSUE THREAD

**Issue by devlinrcg** [Netflix/security_monkey#725]
Hey guys.

Just bumped into an issue when two (2) firewall rules on GCP, from different projects, have the same name. Here is the output:

```
2017-05-11 18:02:53,984 ERROR: Database error processing accounts [u'YOUR_PROJECT_NAME'], cleaning up session. [in /usr/local/src/security_monkey/security_monkey/scheduler.py:34]
Traceback (most recent call last):
  File "/usr/local/src/security_monkey/security_monkey/scheduler.py", line 32, in run_change_reporter
    reporter.run(account, interval)
  File "/usr/local/src/security_monkey/security_monkey/reporter.py", line 60, in run
    monitor.watcher.save()
  File "/usr/local/src/security_monkey/security_monkey/watcher.py", line 483, in save
    item.save(self.datastore)
  File "/usr/local/src/security_monkey/security_monkey/watcher.py", line 632, in save
    ephemeral=ephemeral)
  File "/usr/local/src/security_monkey/security_monkey/datastore.py", line 633, in store
    db.session.commit()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/scoping.py", line 149, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 765, in commit
    self.transaction.commit()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 370, in commit
    self._prepare_impl()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 350, in _prepare_impl
    self.session.flush()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 1879, in flush
    self._flush(objects)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 1997, in _flush
    transaction.rollback(_capture_exception=True)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/langhelpers.py", line 57, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 1961, in _flush
    flush_context.execute()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/unitofwork.py", line 370, in execute
    rec.execute(self)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/unitofwork.py", line 523, in execute
    uow
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/persistence.py", line 59, in save_obj
    mapper, table, update)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/persistence.py", line 510, in _emit_update_statements
    execute(statement, params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 717, in execute
    return meth(self, multiparams, params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/elements.py", line 317, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 814, in _execute_clauseelement
    compiled_sql, distilled_params
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 927, in _execute_context
    context)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1076, in _handle_dbapi_exception
    exc_info
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 185, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 920, in _execute_context
    context)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 425, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (IntegrityError) duplicate key value violates unique constraint "ix_item_arn"
DETAIL:  Key (arn)=(gcp::compute:firewall:get:default-allow-http) already exists.
 'UPDATE item SET arn=%(arn)s, latest_revision_complete_hash=%(latest_revision_complete_hash)s, latest_revision_durable_hash=%(latest_revision_durable_hash)s WHERE item.id = %(item_id)s' {'item_id': 58859, 'latest_revision_durable_hash': 'd3ac50f19959c906528644f201640435', 'arn': u'gcp::compute:firewall:get:default-allow-http', 'latest_revision_complete_hash': 'd3ac50f19959c906528644f201640435'}
```

Does anyone got this before?

**Comment by supertom** [comment]
@devlinrcg Nice find and thanks for reporting.  I suspect we'll need to add the project_id in there to avoid the collisions.
