### ISSUE TITLE
security_group.py TypeError

### ISSUE THREAD

**Issue by ekelson-bcove** [Netflix/security_monkey#862]
Receiving error in security_monkey/auditors/security_group.py. 

TypeError: super(type, obj): obj must be an instance or subtype of type

Not sure if this has to do with the blocker on openstack.  I am only using this for AWS, but I understand there is dependences.

```
2017-11-08 17:40:18,930 INFO: Scheduler started [in build/bdist.linux-x86_64/egg/apscheduler/scheduler.py:574]
2017-11-08 17:40:18,930 INFO: Scheduler has been shut down [in build/bdist.linux-x86_64/egg/apscheduler/scheduler.py:606]
2017-11-08 17:40:22,591 INFO: Started thread pool with 25 core threads and 30 maximum threads [in build/bdist.linux-x86_64/egg/apscheduler/threadpool.py:52]
2017-11-08 17:40:23,454 ERROR: Scheduler Exception: super(type, obj): obj must be an instance or subtype of type [in /usr/local/src/security_monkey/security_monkey/scheduler.py:233]
2017-11-08 17:40:23,455 ERROR: Traceback (most recent call last):
  File "/usr/local/src/security_monkey/security_monkey/scheduler.py", line 212, in setup_scheduler
    rep = Reporter(account=account)
  File "/usr/local/src/security_monkey/security_monkey/reporter.py", line 38, in __init__
    self.all_monitors = all_monitors(account, debug)
  File "/usr/local/src/security_monkey/security_monkey/monitors.py", line 76, in all_monitors
    monitor = Monitor(watcher_class, account, debug)
  File "/usr/local/src/security_monkey/security_monkey/monitors.py", line 25, in __init__
    au = auditor_class([account.name], debug=debug)
  File "/usr/local/src/security_monkey/security_monkey/auditors/security_group.py", line 42, in __init__
    super(SecurityGroupAuditor, self).__init__(accounts=accounts, debug=debug)
TypeError: super(type, obj): obj must be an instance or subtype of type
 [in /usr/local/src/security_monkey/security_monkey/scheduler.py:234]

```

**Comment by monkeysecurity** [comment]
I haven't seen this bug yet.  (If you found this issue because you're running into the same problem, could you add a quick "me too" so I know how to prioritize?  Hopefully it won't get too carried away.)

I'm going to try and work on the openstack bug and then I'll circle back to this one.

**Comment by mstair** [comment]
It is, OpenStackSecurityGroupAuditor inherits from SecurityGroupAuditor, its an issue with the module load order, I removed OpenStackSecurityGroupAuditor in fix PR until I can figure out how to address.

**Comment by monkeysecurity** [comment]
I just merged #861. I'm going to re-deploy and see if I run into further problems.

**Comment by mstair** [comment]
I just did a clean clone on AWS and running. Note, it needs pip install cloudaux\[openstack\] on AWS, I will open another issue to merge in the ImportError catch

**Comment by ekelson-bcove** [comment]
Thank you sir, do I need to rebuild static for this as well or will just recloning the deploy branch work?

**Comment by mstair** [comment]
A reclone or maybe just a pull on your recent clone. Not sure if by static you mean the UI code, which was not affected.

**Comment by monkeysecurity** [comment]
Hey @ekelson-bcove - The biggest change to the UI recently was in my ELB/ALB Auditor PR.  The only UI change in that PR was to some of the dropdowns.  So, rebuild the static folder if you want those dropdowns to be up to date.

**Comment by ekelson-bcove** [comment]
This appears fixed

**Comment by mstair** [comment]
The issue was that my openstack auditor, in the openstack subdir, was also named "security_group.py", if I renamed uniquely, it loads without issue. Will submit a PR to re-enable the openstack security group auditor.

**Comment by monkeysecurity** [comment]
Awesome.  Thanks @mstair
