### ISSUE TITLE
SecurityMonkey stop working

### ISSUE THREAD

**Issue by D4rk4** [Netflix/security_monkey#879]
Can't grab any data. I try do it for our live accounts and for preconfigured exampled accounts from AWS:
```
    (venv) root@oam{/usr/local/src/security_monkey}:monkey find_changes
    2017-11-20 18:27:36,225 INFO: Started thread pool with 25 core threads and 30 maximum threads [in build/bdist.linux-x86_64/egg/apscheduler/threadpool.py:52]
    INFO:apscheduler.threadpool:Started thread pool with 25 core threads and 30 maximum threads
    INFO:botocore.credentials:Credentials found in config file: ~/.aws/config
    INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
    INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
    INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
    INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
    INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
    INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
    INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
    INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
    INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
    INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
    INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
    INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
    INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
    INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
    INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
    INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
    INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
    INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
    INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
    INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
    INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
    INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
    Traceback (most recent call last):
      File "/usr/local/src/security_monkey/venv/bin/monkey", line 11, in <module
        load_entry_point('security-monkey==0.9.3', 'console_scripts', 'monkey')()
      File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/security_monkey-0.9.3-py2.7.egg/security_monkey/manage.py", line 695, in main
        manager.run()
      File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/__init__.py", line 397, in run
        result = self.handle(sys.argv[0], sys.argv[1:])
      File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/__init__.py", line 376, in handle
        return handle(app, *positional_args, **kwargs)
      File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/commands.py", line 145, in handle
        return self.run(*args, **kwargs)
      File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/security_monkey-0.9.3-py2.7.egg/security_monkey/manage.py", line 80, in find_changes
        sm_find_changes(account_names, monitor_names)
      File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/security_monkey-0.9.3-py2.7.egg/security_monkey/scheduler.py", line 52, in find_changes
        (items, exception_map) = cw.slurp()
      File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/security_monkey-0.9.3-py2.7.egg/security_monkey/cloudaux_watcher.py", line 77, in slurp
        regions=self._get_regions(), conn_type='dict')
      File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/security_monkey-0.9.3-py2.7.egg/security_monkey/cloudaux_watcher.py", line 38, in _get_regions
        _, regions = get_regions(account, self.service_name)
      File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/security_monkey-0.9.3-py2.7.egg/security_monkey/decorators.py", line 171, in get_regions
        role = sts.assume_role(RoleArn=arn, RoleSessionName='secmonkey')
      File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/botocore-1.7.47-py2.7.egg/botocore/client.py", line 312, in _api_call
        return self._make_api_call(operation_name, kwargs)
      File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/botocore-1.7.47-py2.7.egg/botocore/client.py", line 605, in _make_api_call
        raise error_class(parsed_response, operation_name)
    botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation: Not authorized to perform sts:AssumeRole
    INFO:root:Shutting down thread pool
```

EDIT: updated for readability

**Comment by mikegrima** [comment]
Hello!

Per the error message, Security Monkey is not able to assume into the destination AWS account `SecurityMonkey` IAM Roles.

Please review the documentation here to ensure that you have the proper IAM configuration: https://github.com/Netflix/security_monkey/blob/develop/docs/iam_aws.md

**Comment by D4rk4** [comment]
@mikegrima how i can debug it? I sure it's not configuration problem on AWS side. Look like problem with botocore connectivity to AWS. I try strace it, i see botocore drop connection after recive cert from sts.amazonaws.com

**Comment by D4rk4** [comment]
@mikegrima Okay, I try run tour command via aws cli and got error `aws: error: argument --role-session-name is required`, but `aws sts assume-role --role-arn arn:aws:iam::<ID>:role/SecurityMonkey --role-session-name secmonkey` working fine, for our all our aws accounts.

**Comment by mikegrima** [comment]
Are you running Security Monkey on the instance or locally?

**Comment by D4rk4** [comment]
It's running inside DigitaOcean droplet (VM). I try update SecMonkey to last git version, but without positive result - still not working crawling.

**Comment by mikegrima** [comment]
How are you seeding your credentials to Security Monkey?  If running on AWS, running an instance with on-instance credentials provides them for you for "free". 

For non-AWS environments, you will need to have an IAM user with (hopefully encrypted) credentials that are then exported into your environment before Security Monkey launches.

**Comment by D4rk4** [comment]
It's from /root/.aws/config file

**Comment by mikegrima** [comment]
Can you confirm that it is using the same credentials that you used earlier?

**Comment by D4rk4** [comment]
Yes, without change. Also AWS CLI get credentials from this file, and working fine. I think maybe SecMonkey not generate session name, required for assume role (change in AWS API)?

**Comment by mikegrima** [comment]
Security Monkey does set this properly, so you are having another issue.

Can you modify your configuration for debug logging:
Set the log level to DEBUG (modify ALL lines in your config file: https://github.com/Netflix/security_monkey/blob/develop/env-config/config.py#L17-L54)

Then, try re-running the watcher.

**Comment by D4rk4** [comment]
I found problem, if role name not defined, by default used " SecurityMonkey" (with leading space)

![_143](https://user-images.githubusercontent.com/1151390/33181966-617c569a-d072-11e7-9e0d-8f8ab7a570a9.png)
![_144](https://user-images.githubusercontent.com/1151390/33181973-6567e922-d072-11e7-8209-42103a26d16c.png)

**Comment by mikegrima** [comment]
Per the code above, there is no leading space in `role_name = 'SecurityMonkey`.  Did you specify a custom role name for the account in question?  

Can you try adding `print()` statements to `account.getCustom("role_name")`?

If that allowed a leading space, then that is a bug.

**Comment by mikegrima** [comment]
@D4rk4 : Have you had time to review?
