### ISSUE TITLE
Security Monkey Not working

### ISSUE THREAD

**Issue by joaquin386** [Netflix/security_monkey#880]
No Matter what I do I received all the time:
monkey fetch_aws_canonical_ids
2017-11-21 11:36:20,952 INFO: Started thread pool with 25 core threads and 30 maximum threads [in build/bdist.linux-x86_64/egg/apscheduler/threadpool.py:52]
INFO:apscheduler.threadpool:Started thread pool with 25 core threads and 30 maximum threads
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
2017-11-21 11:36:21,263 ERROR: [x] Did not receive a proper response back. Check the exception log for details. [in /usr/local/src/security_monkey/security_monkey/common/s3_canonical.py:65]
ERROR:security_monkey:[x] Did not receive a proper response back. Check the exception log for details.
INFO:root:Shutting down thread pool

And on the logs:
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/apscheduler/scheduler.py", line 512, in _run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/src/security_monkey/security_monkey/scheduler.py", line 32, in run_change_reporter
    reporter.run(account, interval)
  File "/usr/local/src/security_monkey/security_monkey/reporter.py", line 56, in run
    (items, exception_map) = monitor.watcher.slurp()
  File "/usr/local/src/security_monkey/security_monkey/cloudaux_watcher.py", line 77, in slurp
    regions=self._get_regions(), conn_type='dict')
  File "/usr/local/src/security_monkey/security_monkey/cloudaux_watcher.py", line 38, in _get_regions
    _, regions = get_regions(account, self.service_name)
  File "/usr/local/src/security_monkey/security_monkey/decorators.py", line 171, in get_regions
    role = sts.assume_role(RoleArn=arn, RoleSessionName='secmonkey')
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/botocore/client.py", line 592, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/botocore/endpoint.py", line 166, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/botocore/endpoint.py", line 150, in create_request
    operation_name=operation_model.name)
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/botocore/signers.py", line 154, in sign
    auth.add_auth(request)
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/botocore/auth.py", line 352, in add_auth
    raise NoCredentialsError
NoCredentialsError: Unable to locate credentials

**Comment by joaquin386** [comment]
Following that document and giving SecurityMonkeyInstanceProfile to the EC2 instance (IAM Role) make the Security Monkey Work. Thanks

I will close the case.
