### ISSUE TITLE
SG S3

### ISSUE THREAD

**Issue by swethareddygalwa** [Netflix/security_monkey#881]
Hi,
can anyone suggest me how to get the score 0 for no issues.
though i dont have any issue i can see the score . 
presently i am using a private IP .

Thanks,

**Comment by mikegrima** [comment]
Hello!  Can you provide additional context on this request?

**Comment by swethareddygalwa** [comment]
Hello Thanks for your reply,
SM should list me all the issues related to this(an S3 bucket granting access to "AllUsers" or a security group allowing 0.0.0.0/0 ) but now it is considering my private IP also an issue, so i have whitelisted them now its not showing me an issue is this the correct way or any other way to avoid it??

**Comment by mikegrima** [comment]
Hello @swethareddygalwa . Security Monkey will flag S3 buckets that grant "AllUsers" access and wide-open security groups.

By default, Security Monkey has no knowledge of your IP space. Thus, if it is not whitelisted, SM will flag it as unknown access.  You will need to flag your IP space to prevent Security Monkey from seeing it as unknown.

**Comment by swethareddygalwa** [comment]
![snip](https://user-images.githubusercontent.com/29959471/33336192-c91d1f62-d434-11e7-9f72-c848356c9bc1.PNG)

Thanks alot..!! For the previous issue.
Can you please help me out with the following issue ?  where i can see all the flags for s3 related to the same.

**Comment by mikegrima** [comment]
For S3, there should be reports at the top menubar to find all S3 buckets that are publicly accessible.

**Comment by swethareddygalwa** [comment]
i cannot find any s3 related in the top menubar.

I have another issue, when i checked logs its running into the following errors
Traceback (most recent call last):
  File "/usr/local/src/security_monkey/security_monkey/scheduler.py", line 137, in _audit_changes
    au.save_issues()
  File "/usr/local/src/security_monkey/security_monkey/auditor.py", line 289, in save_issues
    db.session.commit()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/scoping.py", line 149, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 765, in commit
    self.transaction.commit()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 370, in commit
    self._prepare_impl()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 350, in _prepare_impl
    self.session.flush()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 1879, in flush
    self._flush(objects)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 1997, in _flush
    transaction.rollback(_capture_exception=True)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/langhelpers.py", line 57, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 1961, in _flush
    flush_context.execute()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/unitofwork.py", line 370, in execute
    rec.execute(self)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/unitofwork.py", line 523, in execute
    uow
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/persistence.py", line 64, in save_obj
    mapper, table, insert)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/persistence.py", line 594, in _emit_insert_statements
    execute(statement, params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 717, in execute
    return meth(self, multiparams, params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/elements.py", line 317, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 814, in _execute_clauseelement
    compiled_sql, distilled_params
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 927, in _execute_context
    context)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1076, in _handle_dbapi_exception
    exc_info
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 185, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 920, in _execute_context
    context)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 425, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (IntegrityError) null value in column "fixed" violates not-null constraint
DETAIL:  Failing row contains (1223, 5, Flow Logs not enabled for VPC, null, f, null, null, 2017-11-30 21:08:42.359179, 1812, null, null, null, null, null, null, null).
 'INSERT INTO itemaudit (score, issue, notes, justified, justified_user_id, justification, justified_date, item_id, auditor_setting_id) VALUES (%(score)s, %(issue)s, %(notes)s, %(justified)s, %(justified_user_id)s, %(justification)s, %(justified_date)s, %(item_id)s, %(auditor_setting_id)s) RETURNING itemaudit.id' {'justified_user_id': None, 'justification': None, 'justified_date': datetime.datetime(2017, 11, 30, 21, 8, 42, 359179), 'notes': None, 'score': 5, 'item_id': 1812, 'justified': False, 'issue': 'Flow Logs not enabled for VPC', 'auditor_setting_id': None}
2017-11-30 21:08:43,052 ERROR: Database error processing accounts xxxxxxxxx, cleaning up session. [in /usr/local/src/security_monkey/security_monkey/scheduler.py:146]





Traceback (most recent call last):
  File "/usr/local/src/security_monkey/security_monkey/datastore.py", line 711, in store_exception
    account = Account.query.filter(Account.name == location[1]).one()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2348, in one
    ret = list(self)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2391, in __iter__
    return self._execute_and_instances(context)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2404, in _execute_and_instances
    close_with_result=True)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2395, in _connection_from_session
    **kw)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 843, in connection
    close_with_result=close_with_result)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 847, in _connection_for_bind
    return self.transaction._connection_for_bind(engine)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 298, in _connection_for_bind
    self._assert_active()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 210, in _assert_active
    % self._rollback_exception
InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (IntegrityError) null value in column "fixed" violates not-null constraint

**Comment by mikegrima** [comment]
@swethareddygalwa S3 was recently converged in under the top menu in "Internet Accessible" > "via Resource Policy".

@monkeysecurity any thoughts on the DB error?  It looks like it's barking on an issue's `fixed` field being `null`.

**Comment by monkeysecurity** [comment]
@mikegrima - A `monkey db upgrade` will be required.  This will update any null fields.

This change occurred in DB migration `5bd631a1b748`.

https://github.com/Netflix/security_monkey/blob/develop/migrations/versions/5bd631a1b748_.py#L35
