### ISSUE TITLE
Docker issue

### ISSUE THREAD

**Issue by manasagovindu** [Netflix/security_monkey#897]
## Please make sure that you have checked the boxes: 

- [ ] Review the [Quickstart guide](quickstart.md)
- [ ] Search for both open and closed issues regarding the problem you are experiencing
- [x] **For permissions issues** (Access Denied and credential related errors), please refer to the requisite docs before submitting an issue:
[AWS](iam_aws.md), [GCP](iam_gcp.md), [OpenStack](iam_openstack.md), [GitHub](github_setup.md#access-keys-and-permissions)

## Description of issue:

Hi, i have created a docker image for the security monkey and the container is up and running.when i checked the logs its running into the following errors can anyone help me out ?? and it is not allowing me to create a user and as well to add the amazon account successfully. Thanks

Regards 
Manasa
```
2017-12-21 17:16:34,990 WARNING: Scheduler Exception: (ProgrammingError) permission denied for relation account
 'SELECT account.id AS account_id, account.active AS account_active, account.third_party AS account_third_party, account.name AS account_name, account.notes AS account_notes, account.identifier AS account_identifier, account.account_type_id AS account_account_type_id \nFROM account \nWHERE account.third_party = false AND account.active = true' {} [in /usr/local/src/security_monkey/security_monkey/scheduler.py:231]
2017-12-21 17:16:34,994 WARNING: Traceback (most recent call last):
  File "/usr/local/src/security_monkey/security_monkey/scheduler.py", line 208, in setup_scheduler
    accounts = Account.query.filter(Account.third_party == False).filter(Account.active == True).all()  # noqa
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2279, in all
    return list(self)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2391, in __iter__
    return self._execute_and_instances(context)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2406, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 717, in execute
    return meth(self, multiparams, params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/elements.py", line 317, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 814, in _execute_clauseelement
    compiled_sql, distilled_params
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 927, in _execute_context
    context)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1076, in _handle_dbapi_exception
    exc_info
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 185, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 920, in _execute_context
    context)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 425, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (ProgrammingError) permission denied for relation account
 'SELECT account.id AS account_id, account.active AS account_active, account.third_party AS account_third_party, account.name AS account_name, account.notes AS account_notes, account.identifier AS account_identifier, account.account_type_id AS account_account_type_id \nFROM account \nWHERE account.third_party = false AND account.active = true' {}
 [in /usr/local/src/security_monkey/security_monkey/scheduler.py:232]
2017-12-21 17:16:34,996 ERROR: Encountered exception while logging exception to database: [in /usr/local/src/security_monkey/security_monkey/datastore.py:730]
2017-12-21 17:16:34,996 ERROR: (InternalError) current transaction is aborted, commands ignored until end of transaction block
 'INSERT INTO exceptions (source, occurred, ttl, type, message, stacktrace, region, tech_id, item_id, account_id) VALUES (%(source)s, %(occurred)s, %(ttl)s, %(type)s, %(message)s, %(stacktrace)s, %(region)s, %(tech_id)s, %(item_id)s, %(account_id)s) RETURNING exceptions.id' {'stacktrace': 'Traceback (most recent call last):\n  File "/usr/local/src/security_monkey/security_monkey/scheduler.py", line 208, in setup_scheduler\n    accounts = Account.query.filter(Account.third_party == False).filter(Account.active == True).all()  # noqa\n  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2279, in all\n    return list(self)\n  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2391, in __iter__\n    return self._execute_and_instances(context)\n  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2406, in _execute_and_instances\n    result = conn.execute(querycontext.statement, self._params)\n  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 717, in execute\n    return meth(self, multiparams, params)\n  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/elements.py", line 317, in _execute_on_connection\n    return connection._execute_clauseelement(self, multiparams, params)\n  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 814, in _execute_clauseelement\n    compiled_sql, distilled_params\n  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 927, in _execute_context\n    context)\n  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1076, in _handle_dbapi_exception\n    exc_info\n  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 185, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb)\n  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 920, in _execute_context\n    context)\n  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 425, in do_execute\n    cursor.execute(statement, parameters)\nProgrammingError: (ProgrammingError) permission denied for relation account\n \'SELECT account.id AS account_id, account.active AS account_active, account.third_party AS account_third_party, account.name AS account_name, account.notes AS account_notes, account.identifier AS account_identifier, account.account_type_id AS account_account_type_id \\nFROM account \\nWHERE account.third_party = false AND account.active = true\' {}\n', 'account_id': None, 'region': None, 'occurred': datetime.datetime(2017, 12, 21, 17, 16, 34, 516249), 'tech_id': None, 'source': 'scheduler', 'ttl': datetime.datetime(2017, 12, 31, 17, 16, 34, 516283), 'item_id': None, 'message': "(ProgrammingError) permission denied for relation account\n 'SELECT account.id AS account_id, account.active AS account_active, account.third_party AS account_third_party, account.name AS account_name, account.notes AS account_notes, account.identifier AS account_identifier, account.account_type_id AS account_account_type_id \\nFROM account \\nWHERE account.third_party = false AND account.active = true' {}", 'type': 'ProgrammingError'} [in /usr/local/src/security_monkey/security_monkey/datastore.py:731]
Traceback (most recent call last):
  File "/usr/local/src/security_monkey/security_monkey/datastore.py", line 726, in store_exception
    db.session.commit()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/scoping.py", line 149, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 765, in commit
    self.transaction.commit()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 370, in commit
    self._prepare_impl()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 350, in _prepare_impl
    self.session.flush()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 1879, in flush
    self._flush(objects)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 1997, in _flush
    transaction.rollback(_capture_exception=True)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/langhelpers.py", line 57, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 1961, in _flush
    flush_context.execute()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/unitofwork.py", line 370, in execute
    rec.execute(self)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/unitofwork.py", line 523, in execute
    uow
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/persistence.py", line 64, in save_obj
    mapper, table, insert)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/persistence.py", line 594, in _emit_insert_statements
    execute(statement, params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 717, in execute
    return meth(self, multiparams, params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/elements.py", line 317, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 814, in _execute_clauseelement
    compiled_sql, distilled_params
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 927, in _execute_context
    context)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1076, in _handle_dbapi_exception
    exc_info
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 185, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 920, in _execute_context
    context)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 425, in do_execute
    cursor.execute(statement, parameters)
InternalError: (InternalError) current transaction is aborted, commands ignored until end of transaction block
 'INSERT INTO exceptions (source, occurred, ttl, type, message, stacktrace, region, tech_id, item_id, account_id) VALUES (%(source)s, %(occurred)s, %(ttl)s, %(type)s, %(message)s, %(stacktrace)s, %(region)s, %(tech_id)s, %(item_id)s, %(account_id)s) RETURNING exceptions.id' {'stacktrace': 'Traceback (most recent call last):\n  File "/usr/local/src/security_monkey/security_monkey/scheduler.py", line 208, in setup_scheduler\n    accounts = Account.query.filter(Account.third_party == False).filter(Account.active == True).all()  # noqa\n  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2279, in all\n    return list(self)\n  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2391, in __iter__\n    return self._execute_and_instances(context)\n  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2406, in _execute_and_instances\n    result = conn.execute(querycontext.statement, self._params)\n  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 717, in execute\n    return meth(self, multiparams, params)\n  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/elements.py", line 317, in _execute_on_connection\n    return connection._execute_clauseelement(self, multiparams, params)\n  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 814, in _execute_clauseelement\n    compiled_sql, distilled_params\n  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 927, in _execute_context\n    context)\n  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1076, in _handle_dbapi_exception\n    exc_info\n  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 185, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb)\n  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 920, in _execute_context\n    context)\n  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 425, in do_execute\n    cursor.execute(statement, parameters)\nProgrammingError: (ProgrammingError) permission denied for relation account\n \'SELECT account.id AS account_id, account.active AS account_active, account.third_party AS account_third_party, account.name AS account_name, account.notes AS account_notes, account.identifier AS account_identifier, account.account_type_id AS account_account_type_id \\nFROM account \\nWHERE account.third_party = false AND account.active = true\' {}\n', 'account_id': None, 'region': None, 'occurred': datetime.datetime(2017, 12, 21, 17, 16, 34, 516249), 'tech_id': None, 'source': 'scheduler', 'ttl': datetime.datetime(2017, 12, 31, 17, 16, 34, 516283), 'item_id': None, 'message': "(ProgrammingError) permission denied for relation account\n 'SELECT account.id AS account_id, account.active AS account_active, account.third_party AS account_third_party, account.name AS account_name, account.notes AS account_notes, account.identifier AS account_identifier, account.account_type_id AS account_account_type_id \\nFROM account \\nWHERE account.third_party = false AND account.active = true' {}", 'type': 'ProgrammingError'}
2017-12-21 17:16:35,000 INFO: Scheduler started [in /usr/local/src/security_monkey/venv/lib/python2.7/site-packages/APScheduler-2.1.2-py2.7.egg/apscheduler/scheduler.py:574]
2017-12-21 17:16:35,000 INFO: Scheduler has been shut down [in /usr/local/src/security_monkey/venv/lib/python2.7/site-packages/APScheduler-2.1.2-py2.7.egg/apscheduler/scheduler.py:606]
```

**Comment by mikegrima** [comment]
Hello!

Looking at the log output, this is sticking out: 
```
ProgrammingError: (ProgrammingError) permission denied for relation account
```
Can you verify that the PostgreSQL permissions are correct?  If you are not running an RDS DB, please follow the instructions on the quickstart guide here to ensure that the DB setup is correct: https://github.com/Netflix/security_monkey/blob/develop/docs/quickstart.md#local-postgres that

If you are on RDS, please ensure that you followed the RDS instructions here: https://github.com/Netflix/security_monkey/blob/develop/docs/postgres_aws.md

**Comment by manasagovindu** [comment]
Do we need to have a local DB though we are using AWS RDS ?? 
which we are going to pass AWS RDS credentials as an environment variable after the image is built.

**Comment by mikegrima** [comment]
Are you using RDS or a local DB?

**Comment by manasagovindu** [comment]
using RDS but am passing as an env variable to run the container.

**Comment by manasagovindu** [comment]
The following are the logs 

`2018-01-11 17:04:38,369 DEBUG: Logging exception from scheduler with location: None to the database. [in /usr/local/lib/python2.7/dist-packages/security_monkey-0.9.2-py2.7.egg/security_monkey/datastore.py:696]
2018-01-11 17:04:38,371 ERROR: Encountered exception while logging exception to database: [in /usr/local/lib/python2.7/dist-packages/security_monkey-0.9.2-py2.7.egg/security_monkey/datastore.py:730]
2018-01-11 17:04:38,371 ERROR: (OperationalError) could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
 None None [in /usr/local/lib/python2.7/dist-packages/security_monkey-0.9.2-py2.7.egg/security_monkey/datastore.py:731]
`

**Comment by mikegrima** [comment]
^^ Per your error, it's trying to connect to a database on localhost vs. the RDS DB.

**Comment by manasagovindu** [comment]
solved ..!! thanks @mikegrima is there any specifications for AWS  RDS when i want to add multiple aws accounts.

**Comment by mikegrima** [comment]
You don't need to worry about RDS. You would configure Security Monkey to monitor additional accounts.  Please review the quickstart guide for details.

**Comment by manasagovindu** [comment]
I have DNS name created serperately enabling route53 as false. and passing the dns name as an env variable do i need to configure anything in the config file with FQDN? where i can see the configuration as
FQDN = os.getenv('SECURITY_MONKEY_FQDN', 'ec2-XX-XXX-XXX-XXX.compute-1.amazonaws.com')

Thanks
