### ISSUE TITLE
Help! DB update error securitymonkey

### ISSUE THREAD

**Issue by pklanka** [Netflix/security_monkey#901]
## Please make sure that you have checked the boxes: 

- [X] Review the [Quickstart guide](quickstart.md)
- [X] Search for both open and closed issues regarding the problem you are experiencing
- [X] **For permissions issues** (Access Denied and credential related errors), please refer to the requisite docs before submitting an issue:
[AWS](iam_aws.md), [GCP](iam_gcp.md), [OpenStack](iam_openstack.md), [GitHub](github_setup.md#access-keys-and-permissions)

## Description of issue:

Help - We are trying to update security monkey. I followed verbatim the guide here - https://github.com/Netflix/security_monkey/blob/develop/docs/update.md.

We are having trouble in updating teh database - specifically at this step - "monkey db upgrade"
```
INFO  [alembic.runtime.migration] Running upgrade e0a6af364a3f -> 6245d75fa12, Exceptions Table
INFO  [alembic.runtime.migration] Running upgrade 6245d75fa12 -> 0ae4ef82b244, Distinguishes items created by different auditors of the same type
INFO  [alembic.runtime.migration] Running upgrade 0ae4ef82b244 -> 1a863bd1acb1, Renaming rds to rdssecuritygroup
INFO  [alembic.runtime.migration] Running upgrade 1a863bd1acb1 -> ad23a56abf25, Ability to link issues to other tech type items
INFO  [alembic.runtime.migration] Running upgrade ad23a56abf25 -> d08d0b37788a, Enable custom account types
Traceback (most recent call last):
  File "/usr/local/src/security_monkey/venv/bin/monkey", line 11, in <module>
    load_entry_point('security-monkey==0.9.3', 'console_scripts', 'monkey')()
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/dist-packages/security_monkey-0.9.3-py2.7.egg/security_monkey/manage.py", line 695, in main
    manager.run()
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/dist-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/__init__.py", line 397, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/dist-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/__init__.py", line 376, in handle
    return handle(app, *positional_args, **kwargs)
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/dist-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/commands.py", line 145, in handle
    return self.run(*args, **kwargs)
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/dist-packages/Flask_Migrate-1.3.1-py2.7.egg/flask_migrate/__init__.py", line 177, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/dist-packages/alembic-0.9.6-py2.7.egg/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/dist-packages/alembic-0.9.6-py2.7.egg/alembic/script/base.py", line 425, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/dist-packages/alembic-0.9.6-py2.7.egg/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/dist-packages/alembic-0.9.6-py2.7.egg/alembic/util/compat.py", line 141, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "migrations/env.py", line 72, in <module>
    run_migrations_online()
  File "migrations/env.py", line 65, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/dist-packages/alembic-0.9.6-py2.7.egg/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/dist-packages/alembic-0.9.6-py2.7.egg/alembic/runtime/migration.py", line 330, in run_migrations
    step.migration_fn(**kw)
  File "/usr/local/src/security_monkey/migrations/versions/d08d0b37788a_.py", line 65, in upgrade
    op.create_unique_constraint('account_name_uc', 'account', ['name'])
  File "<string>", line 8, in create_unique_constraint
  File "<string>", line 3, in create_unique_constraint
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/dist-packages/alembic-0.9.6-py2.7.egg/alembic/operations/ops.py", line 399, in create_unique_constraint
    return operations.invoke(op)
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/dist-packages/alembic-0.9.6-py2.7.egg/alembic/operations/base.py", line 319, in invoke
    return fn(self, operation)
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/dist-packages/alembic-0.9.6-py2.7.egg/alembic/operations/toimpl.py", line 135, in create_constraint
    operation.to_constraint(operations.migration_context)
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/dist-packages/alembic-0.9.6-py2.7.egg/alembic/ddl/impl.py", line 180, in add_constraint
    self._exec(schema.AddConstraint(const))
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/dist-packages/alembic-0.9.6-py2.7.egg/alembic/ddl/impl.py", line 118, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 717, in execute
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/ddl.py", line 67, in _execute_on_connection
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 771, in _execute_ddl
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 927, in _execute_context
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1076, in _handle_dbapi_exception
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 185, in raise_from_cause
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 920, in _execute_context
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 425, in do_execute
sqlalchemy.exc.IntegrityError: (IntegrityError) could not create unique index "account_name_uc"
DETAIL:  Key (name)=(AWS Account Production) is duplicated.
 'ALTER TABLE account ADD CONSTRAINT account_name_uc UNIQUE (name)' {}
```

**Comment by mikegrima** [comment]
Interesting...

```
sqlalchemy.exc.IntegrityError: (IntegrityError) could not create unique index "account_name_uc"
DETAIL:  Key (name)=(AWS Account Production) is duplicated.
 'ALTER TABLE account ADD CONSTRAINT account_name_uc UNIQUE (name)' {}
```
^^ It looks like you have a duplicate in there.  It's calling out `AWS Account Production`. Do you have multiple AWS accounts with the same name in your DB?

**Comment by pklanka** [comment]
Changing the name of account after logging into the Postgres helped fix the issue.
