### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by imanandshah** [Netflix/security_monkey#912]
I am a newbie here and I could see issues with security group and policies but nothing apart from it. However i see below errors in the log file. Can some one help? 

```
2018-01-24 04:25:56,921 INFO: Running job "run_change_reporter (trigger: interval[1:00:00], next run at: 2018-01-24 04:25:56 UTC)" (scheduled at 2018-01-24 04:25:56.913725+00:00) [in /usr/local/src/security_monkey/venv/lib/python2.7/site-packages/APScheduler-3.5.0-py2.7.egg/apscheduler/executors/base.py:123]
2018-01-24 05:04:36,513 ERROR: Job "run_change_reporter (trigger: interval[1:00:00], next run at: 2018-01-24 05:25:56 UTC)" raised an exception [in /usr/local/src/security_monkey/venv/lib/python2.7/site-packages/APScheduler-3.5.0-py2.7.egg/apscheduler/executors/base.py:131]
Traceback (most recent call last):
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/APScheduler-3.5.0-py2.7.egg/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/src/security_monkey/security_monkey/scheduler.py", line 30, in run_change_reporter
    reporter.run(account, interval)
  File "/usr/local/src/security_monkey/security_monkey/reporter.py", line 61, in run
    monitor.watcher.save()
  File "/usr/local/src/security_monkey/security_monkey/watcher.py", line 486, in save
    item.save(self.datastore)
  File "/usr/local/src/security_monkey/security_monkey/watcher.py", line 635, in save
    ephemeral=ephemeral)
  File "/usr/local/src/security_monkey/security_monkey/datastore.py", line 635, in store
    item.latest_revision_complete_hash = self.hash_config(config)
  File "/usr/local/src/security_monkey/security_monkey/datastore.py", line 550, in hash_config
    item = sub_dict(config)
  File "/usr/local/src/security_monkey/security_monkey/common/utils.py", line 54, in sub_dict
    for k in d:
TypeError: 'NoneType' object is not iterable
```

**Comment by mikegrima** [comment]
Closing as AP Scheduler was removed.
