### ISSUE TITLE
find_changes crash when cannot read info

### ISSUE THREAD

**Issue by D4rk4** [Netflix/security_monkey#963]
```
DEBUG:security_monkey:Skipping ('ec2image', u'Prod-6581', u'eu-central-1', u'ami-******') due to an item-level exception 'Problem Connecting to ec2image/Prod-6581/ami-ffb47290:\nAn error occurred (UnauthorizedOperation) when calling the DescribeImageAttribute operation: You are not authorized to perform this operation.'.
2018-02-26 11:53:23,965 INFO: 0 deleted EC2 Images in [u'Prod-6581'] [in /usr/local/src/security_monkey/security_monkey/watcher.py:497]
INFO:security_monkey:0 deleted EC2 Images in [u'Prod-6581']
2018-02-26 11:53:23,966 INFO: 0 created EC2 Images in [u'Prod-6581'] [in /usr/local/src/security_monkey/security_monkey/watcher.py:498]
INFO:security_monkey:0 created EC2 Images in [u'Prod-6581']
2018-02-26 11:53:23,967 INFO: 0 changed EC2 Images in [u'Prod-6581'] [in /usr/local/src/security_monkey/security_monkey/watcher.py:515]
INFO:security_monkey:0 changed EC2 Images in [u'Prod-6581']
2018-02-26 11:53:24,245 DEBUG: [-->] Auditing account: Prod-6581, technology: ec2image [in /usr/local/src/security_monkey/security_monkey/task_scheduler/tasks.py:236]
DEBUG:security_monkey:[-->] Auditing account: Prod-6581, technology: ec2image
2018-02-26 11:53:24,270 DEBUG: Asked to audit 8 Objects [in /usr/local/src/security_monkey/security_monkey/auditor.py:660]
DEBUG:security_monkey:Asked to audit 8 Objects
2018-02-26 11:53:24,272 DEBUG: methods: [<bound method EC2ImageAuditor.check_friendly_cross_account of <ec2_image.EC2ImageAuditor object at 0x7f17ca297850>>, <bound method EC2ImageAuditor.check_internet_accessible of <ec2_image.EC2ImageAuditor object at 0x7f17ca297850>>, <bound method EC2ImageAuditor.check_thirdparty_cross_account of <ec2_image.EC2ImageAuditor object at 0x7f17ca297850>>, <bound method EC2ImageAuditor.check_unknown_cross_account of <ec2_image.EC2ImageAuditor object at 0x7f17ca297850>>] [in /usr/local/src/security_monkey/security_monkey/auditor.py:667]
DEBUG:security_monkey:methods: [<bound method EC2ImageAuditor.check_friendly_cross_account of <ec2_image.EC2ImageAuditor object at 0x7f17ca297850>>, <bound method EC2ImageAuditor.check_internet_accessible of <ec2_image.EC2ImageAuditor object at 0x7f17ca297850>>, <bound method EC2ImageAuditor.check_thirdparty_cross_account of <ec2_image.EC2ImageAuditor object at 0x7f17ca297850>>, <bound method EC2ImageAuditor.check_unknown_cross_account of <ec2_image.EC2ImageAuditor object at 0x7f17ca297850>>]
Traceback (most recent call last):
  File "/usr/local/src/security_monkey/venv/bin/monkey", line 11, in <module>
    load_entry_point('security-monkey', 'console_scripts', 'monkey')()
  File "/usr/local/src/security_monkey/security_monkey/manage.py", line 775, in main
    manager.run()
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/flask_script/__init__.py", line 397, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/flask_script/__init__.py", line 376, in handle
    return handle(app, *positional_args, **kwargs)
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/flask_script/commands.py", line 145, in handle
    return self.run(*args, **kwargs)
  File "/usr/local/src/security_monkey/security_monkey/manage.py", line 89, in find_changes
    manual_run_change_finder(account_names, monitor_names)
  File "/usr/local/src/security_monkey/security_monkey/task_scheduler/tasks.py", line 180, in manual_run_change_finder
    find_changes(account, tech)
  File "/usr/local/src/security_monkey/security_monkey/task_scheduler/tasks.py", line 213, in find_changes
    audit_changes([account_name], [monitor_name], False, debug)
  File "/usr/local/src/security_monkey/security_monkey/task_scheduler/tasks.py", line 237, in audit_changes
    _audit_changes(account, monitor.auditors, send_report, debug)
  File "/usr/local/src/security_monkey/security_monkey/task_scheduler/tasks.py", line 289, in _audit_changes
    au.audit_objects()
  File "/usr/local/src/security_monkey/security_monkey/auditor.py", line 674, in audit_objects
    method(item)
  File "/usr/local/src/security_monkey/security_monkey/auditors/ec2_image.py", line 25, in check_friendly_cross_account
    accounts = {lp.get('UserId', lp.get('Group')) for lp in item.config.get('LaunchPermissions')}
TypeError: 'NoneType' object is not iterable

 
```

**Comment by D4rk4** [comment]
I use standard SecurityMonkey role form installation guide for enumerate, it's not included "ec2:DescribeImageAttribute" rights.

**Comment by mikegrima** [comment]
`ec2:DescribeImageAttribute` is documented: https://github.com/Netflix/security_monkey/blob/develop/docs/iam_aws.md#creating-securitymonkey-role

I am going to submit a PR to add some proper `None` avoidance.

**Comment by mikegrima** [comment]
PR #964 to prevent `NoneType`s.
